### ISSUE TITLE
[BUG] inconsistent argument name

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/NVTabular#100]
**Describe the bug**

This is a trivial bug. Sorry in advance if I misunderstand...

In the example notebook (https://github.com/NVIDIA/NVTabular/blob/master/examples/optimize_criteo.ipynb), `nvt.dataset()` is called with one argument, `dtypes`. However, in the reader class, `CSVFileReader`, `dtype` is called like below. A character "s" is missing.

```
dtype = kwargs.get("dtype", None)
```
https://github.com/NVIDIA/NVTabular/blob/master/nvtabular/io.py#L175

Either example or reader should be fixed.

**Steps/Code to reproduce bug**

Please run the example.

**Expected behavior**

Given argument is used appropriately.

**Environment details (please complete the following information):**

 - Environment location: Docker
 - Method of NVTabular install: Docker
   - NGC's container image: hash is `1567a4251e7f`.
   - Launch command: `sudo docker run --gpus=all --rm -it -v $(pwd):/ws -v /path/to/data/:/data -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_PTRACE nvcr.io/nvidia/nvtabular:0.1 /bin/bash`
 
**Additional context**

N/A.

Thanks!

**Comment by jperez999** [comment]
The `dtype` and `dtypes` arguments are treated as separate keyword arguments. `dtype` is used by the underlying cudf library while `dtypes` is something that NVTabular introduced to handled string hex to int transforms. Even though dtype is able to handle some hex string to int transforms, if the data is not in the correct format(i.e. for hex string must start 0x) it is not recognized. To support the Criteo dataset we introduced the dtypes mechanism.

**Comment by lazykyama** [comment]
Thanks for your comment! Understood.
