### ISSUE TITLE
[BUG] Inconsistent behavior with NVT + cudf 

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#1013]
**Describe the bug**
I am running the code below and each time when I restart the kernel an rerun these scripts, I get a different `len(df)`. 

**Steps/Code to reproduce bug**

```python
raw_df = cudf.read_csv('2019-Oct.csv') 
raw_df['event_time_dt'] = raw_df['event_time'].astype('datetime64[s]')
raw_df['event_time_ts']= raw_df['event_time_dt'].astype('int')
raw_df = raw_df[raw_df['user_session'].isnull()==False]

cols = list(raw_df.columns)
cols.remove('user_session')

#  load data 
df_event = nvt.Dataset(raw_df) 
# categorify features 
cat_feats = ['user_session'] >> nvt.ops.Categorify()

workflow = nvt.Workflow(cols + cat_feats)
workflow.fit(df_event)
df = workflow.transform(df_event).to_ddf().compute()

df_firstsession = df.groupby('user_session').agg({'event_time_ts': 'min'}).reset_index()
df_firstsession = df_firstsession.rename(columns={'event_time_ts':'event_time_ts_min'})

df_merged = df.merge(df_firstsession, on=['user_session'], how = 'left')

# remove the first interaction
df = df_merged[~((df_merged['event_time_ts'] == df_merged['event_time_ts_min']))]

df = df.drop(['event_time_ts_min'],  axis=1)

df = df.sort_values(['user_session', 'event_time_ts']).reset_index(drop=True)
print("Count with in-session repeated interactions: {}".format(len(df)))
# Sorts the dataframe by session and timestamp, to remove consecutive repetitions
df['product_id_past'] = df['product_id'].shift(1).fillna(0)
df['session_id_past'] = df['user_session'].shift(1).fillna(0)
#Keeping only no consecutive repeated in session interactions
df = df[~((df['user_session'] == df['session_id_past']) & \
             (df['product_id'] == df['product_id_past']))]
print("Count after removed in-session repeated interactions: {}".format(len(df)))
del(df['product_id_past'])
del(df['session_id_past'])

print(len(df))
```

Data can be found here: 

https://drive.google.com/file/d/1pRXfGbBMNn_JdAL9ynGi1253_xUl3IoX/view

**Expected behavior**
`len(df)` or  `df.shape` should always give the same length for the dataset from different runs when the same operations are applied.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]  Docker image on NGC 
 - Method of NVTabular install: [conda, Docker, or from source] Docker 
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used 

I am using `nvstaging/merlin/merlin-pytorch-training:nightly` image. Cudf version is:  `21.06.01+0.g101fc0fda4.dirty`
 

**Additional context**

**Comment by benfred** [comment]
@rnyak can we close this? This doesn't seem like something we can fix on nvt
