### ISSUE TITLE
[DEP] Handle future pyarrow-API deprecations

### ISSUE THREAD

**Issue by rjzamora** [NVIDIA/NVTabular#103]
**Describe the bug**
Note that this is not really a "bug" **yet**, but will be in the future :)

Recent/future efforts in pyarrow will eventually cause problems for some of our dask-based I/O logic.  The critical changes include:

- Deprecation of [pyarrow.compat](https://github.com/apache/arrow/blob/cfe114478d0c90b0822aec1c8c24635c3d35330e/python/pyarrow/compat.py#L24), which both dask and NVTabuar use for "random" file naming.
- Replacement of the `ParquetDataset` API with a new [pyarrow.dataset](https://github.com/apache/arrow/blob/cfe114478d0c90b0822aec1c8c24635c3d35330e/python/pyarrow/dataset.py#L494) API.  For now, much of the original functionality is still supported.  However, it seems that the plan is to change the legacy API into a [thin dataset-API shim layer](https://github.com/apache/arrow/blob/cfe114478d0c90b0822aec1c8c24635c3d35330e/python/pyarrow/parquet.py#L1374) (and to ultimately stop supporting and deprecate `ParquetDataset`)

**TODO**:
- [ ] Stop using `pyarrow.compat` API (`guid` for file naming)
- [ ] Switch to `pyarrow.dataset` API for newer pyarrow versions (Allow `ParquetDataset` for `pyarrow<0.17`)

Note that these same steps need to be addressed in the upstream `dask`/`cudf` libraries, but those projects are waiting on a bit more functionality from the *new* API (`nvtabular` can make the changes sooner).

**Comment by benfred** [comment]
The first change should be super straightforward - just switch from using guid to using ```uuid.uuid4()``` from the python std library.

I'm all for just requiring pyarrow >= 0.17 and switching to the new dataset api =)
