### ISSUE TITLE
[QST] How to efficiently read data from Google Cloud Storage (gs://)?

### ISSUE THREAD

**Issue by leiterenato** [NVIDIA/NVTabular#1088]
**What is your question?**

I am using NVTabular to do the preprocessing of large parquet files stored in a bucket in Google Cloud Storage (~11GB each file - criteo dataset).
The end goal is to find a solution to efficiently preprocess large volumes of data (> 100TB) reading parquet files directly from GCS (protocol `gs`).

For an initial benchmark I used [this script](https://github.com/NVIDIA/NVTabular/blob/main/bench/examples/dask-nvtabular-criteo-benchmark.py) from the NVTabular repository.
In [line 226](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/bench/examples/dask-nvtabular-criteo-benchmark.py#L216) it creates a Dataset (universal external-data wrapper) from a list of GCS paths which instantiates a '[PaquetDatasetEngine](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/nvtabular/io/parquet.py#L59)' as '[self.engine](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/nvtabular/io/dataset.py#L282)'.

NVTabular methods [.fit](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/bench/examples/dask-nvtabular-criteo-benchmark.py#L221) and [.transform](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/bench/examples/dask-nvtabular-criteo-benchmark.py#L225) receive the Dataset instance and they both call the method [Dataset.to_dff](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/nvtabular/workflow/workflow.py#L177) which returns the result of [dask_cudf.read_parquet](https://github.com/NVIDIA/NVTabular/blob/6635972632de86061274558e0a3e224e8254b6ba/nvtabular/io/parquet.py#L217).
The problem is that for each call it opens the entire file from GCS with [fs.open(path, mode="rb")](https://github.com/rapidsai/cudf/blob/ae440465c2d8c0b299261923083fa1fe16b2f038/python/dask_cudf/dask_cudf/io/parquet.py#L70) and if it is reading parts of the file, it is opened multiple times.

As cuDF uses fsspec (and gcsfs for `gs` protocol), would it be possible to read parts of the file in parallel in GCS instead of opening the entire file?
GCS supports parallel random access to files in a bucket, so I did a quick test and it would be much fasters to use [fsspec.filesystem('gs').read_block](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/spec.html#AbstractFileSystem.read_block) instead of just [fsspec.open](https://filesystem-spec.readthedocs.io/en/latest/api.html?highlight=read_block#fsspec.open).

Example:
import fsspec as fs
a = fs.filesystem('gs')
a.read_block('gs://<mybucket>/criteo-parque/day_0.parquet', 10000, 1000)

I am using [this Dockerfile](https://github.com/jarokaz/merlin-on-vertex/blob/main/nvtabular_gcs_performance/Dockerfile) definition for the tests.

**Comment by rjzamora** [comment]
Note that #1119 should get us a lot closer to where we want to be on GCS performance.  In the long term, it will be best if cudf can efficiently work with Arrow-based file object, and in the "medium" term, we would want the fsspec data-transfer optimizations to live in cudf or Dask. However, for now, that PR exposes a nice location for use to explore and test remote data-transfer optimizations.

**Comment by benfred** [comment]
Fixed by #1119

**Comment by leiterenato** [comment]
Thank you very much!  
This is great news ...
