### ISSUE TITLE
dask and other library versions conflict when Rapids 21.08 and NVtabular are installed in the same Conda environment

### ISSUE THREAD

**Issue by mgoel-absci** [NVIDIA/NVTabular#1092]
**Is your feature request related to a problem? Please describe.**
I am trying to use Rapids 21.08 and NVTabular in the same Conda environment.  There are a few version conflicts for Dask and other libraries
**Describe the solution you'd like**
NVT and Rapids 21.08 should work together in the same environment
**Describe alternatives you've considered**
I installed NVT using the environment.yaml file for python3.8 and cudatoolkit 11.2.  Changed the version numbers for the dependencies to match Rapids.
**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by benfred** [comment]
@mgoel-absci this is fixed by https://github.com/NVIDIA/NVTabular/pull/1152 - can you try it out now?

**Comment by mgoel-absci** [comment]
Works now Ben.  Thanks a lot.

Manan

**Comment by mgoel-absci** [comment]
Works now.  Thanks a lot for addressing this.
