### ISSUE TITLE
[DOC] Update the Rossman example notebook to be NVTabular only

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA/NVTabular#113]
Evaluate the notebook:
https://github.com/NVIDIA/NVTabular/blob/master/examples/rossmann-store-sales-preproc.ipynb

And using the new udf string ops recreate this notebook in NVTabular.  If additional ops are required please create an issue for that op.

**Comment by rnyak** [comment]
@EvenOldridge @benfred the Rossmann notebook requires couple of date time features from cuDF to convert it to cudf, and/or NVTabular. cuDF does not have such functionality. One issue was created by Julio a while ago:
https://github.com/rapidsai/cudf/issues/4908

**Comment by EvenOldridge** [comment]
As per above, can we treat it like a string instead of date time and pull out the appropriate columns.

**Comment by rnyak** [comment]
> As per above, can we treat it like a string instead of date time and pull out the appropriate columns.

to determine `week`, we need more than that.

**Comment by EvenOldridge** [comment]
Isn't week an integer division of days?
