### ISSUE TITLE
[BUG] CUDARuntimeError on the Merlin Docker CI container

### ISSUE THREAD

**Issue by lesnikow** [NVIDIA/NVTabular#1148]
**Describe the bug**

I ran the Merlin Docker CI container with tag: latest. I get a `CUDARuntimeError` when I run `pytest` in the `/nvtabular` directory.  

**Steps/Code to reproduce bug**

Here is a minimal, complete, verified example to reproduce this bug:

1. `docker run --gpus '"device=0"' -it  nvcr.io/nvstaging/merlin/merlin_ci_runner:latest /bin/bash`

2. `cd /nvtabular/`

3. `pytest .`

This produces a `CUDARuntimeError: cudaErrorCompatNotSupportedOnDevice: forward compatibility was attempted on non supported HW` error with the following traceback:

<details>
```ImportError while loading conftest '/nvtabular/tests/conftest.py'.
tests/conftest.py:31: in <module>
    import cudf
/usr/local/lib/python3.8/dist-packages/cudf/__init__.py:4: in <module>
    validate_setup()
/usr/local/lib/python3.8/dist-packages/cudf/utils/gpu_utils.py:63: in validate_setup
    raise e
/usr/local/lib/python3.8/dist-packages/cudf/utils/gpu_utils.py:60: in validate_setup
    gpus_count = getDeviceCount()
rmm/_cuda/gpu.pyx:134: in rmm._cuda.gpu.getDeviceCount
    ???
E   rmm._cuda.gpu.CUDARuntimeError: cudaErrorCompatNotSupportedOnDevice: forward compatibility was attempted on non supported HW
```
</details>

**Expected behavior**

The expected behavior is that `pytest` should be able to run all found tests in the `nvtabular/` directory.

**Environment details (please complete the following information):**
 - Environment location: The Docker Merlin CI container with tag `latest` and image id `786aa04c3187` 

 - Method of NVTabular install: NVTabular was installed by the maintainers of the container image. 

A minimal `docker run` command that reproduces this problem is:

`docker run --gpus '"device=0"' -it  nvcr.io/nvstaging/merlin/merlin_ci_runner:latest /bin/bash`

The `docker pull` command used to acquire this Docker image is: 

`docker pull nvcr.io/nvstaging/merlin/merlin_ci_runner:latest`

 
 

**Additional context**

On the host OS, `uname -a` gives the following:

 `Linux nv-pc 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

while `nvidia-smi` on the host OS gives:

<details>
```Fri Sep 24 11:12:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   39C    P8    14W / 215W |      1MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:42:00.0  On |                  N/A |
| 28%   37C    P8    10W / 180W |   1165MiB /  8118MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A      1990      G   /usr/lib/xorg/Xorg                 18MiB |
|    1   N/A  N/A      2294      G   /usr/bin/gnome-shell               69MiB |
|    1   N/A  N/A      3201      G   /usr/lib/xorg/Xorg                395MiB |
|    1   N/A  N/A      3311      G   /usr/lib/firefox/firefox          645MiB |
|    1   N/A  N/A      3565      G   /usr/lib/firefox/firefox            1MiB |
|    1   N/A  N/A      3689      G   /usr/lib/firefox/firefox            1MiB |
|    1   N/A  N/A      3715      G   /usr/lib/firefox/firefox            1MiB |
|    1   N/A  N/A      7810      G   ...AAAAAAAAA= --shared-files       24MiB |
+-----------------------------------------------------------------------------+
```
</details>k

**Comment by albert17** [comment]
@lesnikow 

This is probably to cudf not being compiled properly for all the architectures. 

This change has just been merged: https://github.com/NVIDIA-Merlin/Merlin/pull/52 Merlin containers are being re-built right now and all should be working. If so, I will add the change to merlin_ci container and this problem should be solved. 

I will keep you posted.

**Comment by lesnikow** [comment]
@albert17 Thank you, this is very good to know. In this case, let me do another docker pull to update this container image, and see if this will resolve this issue.

**Comment by benfred** [comment]
I believe this is fixed - @lesnikow can you re-open if this is still occurring?
