### ISSUE TITLE
[OP] CountEncoding

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA/NVTabular#116]
**Is your feature request related to a problem? Please describe.**
CountEncoding is a common feature engineering technique for categorical features in tabular data. The OPs calculate the popularity / number of occurrences in the dataset.

**Describe the solution you'd like**
Count the frequency of the categorical value and create a new column (feature) with it. Count encoded values can be normalized (sum of values to 100%).

There are two different mode:
1. CountEncoding is calculated with both training and validation dataset combined
2. CountEncoding is calculated for training and validation dataset separately

**Describe alternatives you've considered**
I am not sure, if the current workflow enables both mode of CountEncoding.
I think, I would add a separate Op for normalizing the values to 0-1.

**Additional context**
Example Implementation can be found here:
https://github.com/rapidsai/recsysChallenge2020/blob/master/Baselines/DASK-XGB/Demo-e2e-multi-CPU.ipynb : CountEncoder (non normalized) and FrequencyEncoder (normalised)
https://github.com/rapidsai/recsysChallenge2020/blob/master/final_models/XGB1334/XGB1334-submit-singleGPU.ipynb : count_encode_cudf_v2

**Comment by benfred** [comment]
Can this be done with the GroupBy operator - and using the counts stat it calculates?

**Comment by benfred** [comment]
We should be able to get this done with min-max scaling and operator chaining - just need to validate.

**Comment by bschifferer** [comment]
> We should be able to get this done with min-max scaling and operator chaining - just need to validate.

CountEncoding works with the GroupBy operator. Chaining of operators worked.
The original code uses LengthScaling (dataset length) - after some consideration, I think we dont need that feature:
1. MinMax Scaling is probably equivalent/really close to LengthScaling
2. Decision Trees should work independent of the scaling
