### ISSUE TITLE
[FEA] Dask Workflow with no client

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#119]
We should be able to run the dask workflow with no client passed in.  This should help out with the code coverage issues we've been seeing, and mean that are existing examples will work as is with Dask.

**Comment by rjzamora** [comment]
I just started looking into this and will try to post a PR tomorrow.

Overall, I am noticing that this may require a few significant changes throughout nvtabular.  It is pretty "easy" to handle `client=None` within `DaskWorkflow` (and in the ops), but that means we will **always** be using `DaskWorkflow`.  When the distributed client is excluded, nvtabular will still use a dask-based workflow, but with a `"synchronous"` scheduler (the client, scheduler and worker are executed on the same process).  Note that I can certainly add **another** switch to select the `BaseWorkflow`,  but we will need to remove (public) access to that class soon anyway.  

We can use some of the cleanup in #114 to make an "all-DaskWorkflow" approach work for most cases.  However, we will need to make sure that anything expecting a `GPUDatasetIterator` is updated to explicitly convert an input dataset objects into an iterator (`using dataset.to_iter`).   This includes both dataloaders (which definitely seem to be using `GPUDatasetIterator` explicitly).  Also, and `BaseWorkflow` code that has been overwritten by `DaskWorkflow` will not be publically accessible (so we need to see what breaks).
