### ISSUE TITLE
[BUG] `get_embedding_size` broken by recent changes to encoder statistics (`workflow.stats["categories"]`)

### ISSUE THREAD

**Issue by rdipietro** [NVIDIA/NVTabular#132]
The first argument of `get_embedding_size` is a `dict` that represents "The encoding statistics of the categorical variables (ie. from workflow.stats["categories"])"

The problem is that what we refer to as "encoding statistics" (`workflow.stats["categories"]`) was recently changed. Before, it mapped strings (categorical variable names) to integers (cardinalities), but now it maps strings (categorical variable names) to strings (file paths that store data frames where each row contains a category name and its integer-valued equivalent).

`get_embedding_size` needs to be updated to work with this new definition of encoding statistics.

(The current behavior is to fail with the error `TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'float'`)

**Comment by benfred** [comment]
This will be fixed by https://github.com/NVIDIA/NVTabular/pull/128

**Comment by benfred** [comment]
This is fixed in master now
