### ISSUE TITLE
[FEA] Run example notebooks as part of our CI

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#136]
**Is your feature request related to a problem? Please describe.**

There has been a couple of times now where we've introduced breaking changes and not updated our example notebooks (for instance #85). We should automatically test and run our notebooks as part of our CI

**Describe the solution you'd like**

We should run our notebooks on tiny datasets to make sure that they work as advertised on every PR

**Comment by rdipietro** [comment]
Is it acceptable for tests to take a long time? Or are you thinking we can add small bits to all notebooks (e.g. via an environment variable) that runs using only a small subset of data / iterations?

**Comment by benfred** [comment]
I'd like to keep the tests on our PR's happening in less than 5 minutes - so I don't want to run these tests on the full dataset as part of our CI. Testing on large datasets should also happen automatically - but not as part of the CI process, and instead I think we should run integration tests looking for performance regressions nightly.

For running CI on our notebooks, I'm thinking that we can pass in a toy dataset  (< 10K rows) for each example notebook -  potentially by setting an environment variable which the notebook picks up.

I'd also like to run tests like flake8/black etc on our notebooks to automatically check the style of the python code. I think we can do this by doing something like ```jupyter nbconvert --stdout --to python --PythonExporter.exclude_markdown=True ./examples/*.ipynb | flake8``` as part of our CI
