### ISSUE TITLE
[BUG] Rossmann notebook broken by recent changes to dataset / Dataset

### ISSUE THREAD

**Issue by rdipietro** [NVIDIA/NVTabular#137]
Rossmann notebook broken by recent dataset changes (old version `dataset`, new version `Dataset` with a different call signature)

**Comment by rdipietro** [comment]
This is true both at the dataset level (e.g., calling `nvt.dataset`) and at the framework level.

(Once the initial calls to `nvt.dataset` are fixed, the TensorFlow and fast.ai versions both brake because of incompatibility with the new intended usage of `nvt.Dataset`, which for example is no longer iterable.)

**Comment by EvenOldridge** [comment]
@alecgunny can you assess the TF version
@jperez999 likewise for PyTorch.

@rdipietro to add more details

**Comment by benfred** [comment]
Thanks for the bug report! #140 should fix (also this is another example that we should automatically running our CI against notebooks as in #136 =)
