### ISSUE TITLE
[FEA] cudf  support for read/write parquet files with nested list columns

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#139]
Relevant issue was created: https://github.com/rapidsai/cudf/issues/5665

**Comment by rnyak** [comment]
This cudf PR is relevant:  https://github.com/rapidsai/cudf/pull/5629

**Comment by benfred** [comment]
cudf supports reading/writing parquet files with list columns in the latest 0.16 nightly.
