### ISSUE TITLE
[BUG] Rossmann notebook still broken from recent sweeping changes to NVTabular

### ISSUE THREAD

**Issue by rdipietro** [NVIDIA/NVTabular#146]
After the recent dataset changes / dask API compatibility changes, and after the recent fix to the Rossmann notebook (https://github.com/NVIDIA/NVTabular/pull/140), which made the notebook run without runtime errors, convergence and final results are still much worse than what they once were.

This is true for both the TensorFlow and fast.ai implementations, although the fast.ai implementation is affected more harshly.

It's difficult to be more specific about this bug, because I do not know what the root cause is, but I thought it's worth reporting, so that someone familiar with the dataset / dask changes can investigate.

Steps to reproduce:

First, roll back to an old commit, before dataset / dask changes, but incorporate the changes to the Rossmann notebook that fixed bugs, improved organization, etc.:

```
# d44defa Refactor get_emb_sz (#110)
git checkout d44defa

# c179905 Merge pull request #123 from NVIDIA/vinhn-demo-notebook
git checkout c179905 -- examples/rossmann-store-sales-example.ipynb
```

In this setting, if we run the notebook 3 times, training is always stable, and we get final RMSPEs of
- 0.19, 0.19, 0.21 for Tensorflow
- 0.19, 0.22, 0.21 for fast.ai

Next, come back to the more recent commit, after dataset / dask changes, and run the notebook:

```
# 294b480 Rossmann notebook fixes (#140)
git checkout 294b480
```

In this setting, if we run the notebook 3 times, training is no longer stable, and we get final RMSPEs of
- 0.27 0.29 0.29 for TensorFlow
- 0.69 0.42 0.48 for fast.ai

**Comment by rdipietro** [comment]
Follow up to help determine whether this is due to data preprocessing or data loading:

What happens if we

1. use the old code (`d44defa`) to preprocess the data, all the way up to forming `parquet` files with our `Workflow`, but then
2. use the new code (right now `ff5bb4b`) to continue with data loading and training?

Note: After (1), (2) is carried out by rerunning and having the `Workflow` write out to a temporary `PREPROCESS_DIR`, and after this, resetting `PREPROCESS_DIR` to continue with loading/training using prior `Workflow` outputs from step (1).

If we carry this out 5 times, we get final RMSPEs of

- 0.17 0.18 0.19 0.17 0.19 for TensorFlow
- 0.37 0.19 0.23 0.19 0.23 for fast.ai

Primary takeaway: Results are significantly better for both TensorFlow and fast.ai if we use 'old' preprocessing, which suggests that the issue is with the preprocessing phase, not the data loading / training phase

Secondary takeaway: fast.ai results are slightly worse than TensorFlow results, even when using the old preprocessing. Why is this? I can address this (and similarly for the [PyTorch version](https://github.com/NVIDIA/NVTabular/pull/147)) once the preprocessing issues are resolved and once https://github.com/NVIDIA/NVTabular/pull/147 is merged

**Comment by rjzamora** [comment]
Thanks for investigating @rdipietro - It seems reasonable to me that there could be a bug/problem in one of the dask-based operations.  There is not much "validation" in the unit tests - mostly high-level sanity checks.

I will try to investigate the pre-processing phase of the notebook later tonight or tomorrow and see if there are any obvious problems with the processed dataset.  My understanding is that the dataset is small enough to do preprocessing with cudf/pandas alone.  Is that right?

**Comment by rdipietro** [comment]
Yes, it's small and can be processed entirely in memory.

Right now, the 'pre pre processing' is done in `examples/rossmann-store-sales-preproc.ipynb` using pandas, which writes out 3 CSVs (one for each split). This process is fixed for every experiment mentioned in this issue.

Then 'preprocessing' (using a `Workflow` to convert the CSVs to parquet files) is carried out in `examples/rossmann-store-sales-example.ipynb`. The most relevant lines (from the newest version of the notebook) are

```
train_dataset = nvt.Dataset(TRAIN_PATH, gpu_memory_frac=GPU_MEMORY_FRAC, columns=COLUMNS)
valid_dataset = nvt.Dataset(VALID_PATH, gpu_memory_frac=GPU_MEMORY_FRAC, columns=COLUMNS)

...

proc.apply(train_dataset, apply_offline=True, record_stats=True, output_path=PREPROCESS_DIR_TRAIN, shuffle=True, out_files_per_proc=2)
proc.apply(valid_dataset, apply_offline=True, record_stats=False, output_path=PREPROCESS_DIR_VALID, shuffle=False)
```

**Comment by rjzamora** [comment]
Thanks for the info!

I am trying this on top of #160 (with fastai), and my results seem reasonable.

```
epoch | train_loss | valid_loss | exp_rmspe | time
-- | -- | -- | -- | --
0 | 15.013089 | 5.290609 | 0.876375 | 00:01
1 | 9.143460 | 4.845906 | 0.875166 | 00:01
2 | 6.468053 | 1.874029 | 0.730170 | 00:01
3 | 4.726548 | 1.386171 | 0.676081 | 00:01
...
22 | 0.070353 | 0.041986 | 0.207072 | 00:01
23 | 0.064311 | 0.041882 | 0.204949 | 00:01
24 | 0.059516 | 0.039038 | 0.205314 | 00:01
```

`exp_rmspe` is ranging from 0.17-0.21 from run to run.
Note that the `Dataset` API calls do need to change to get things to work correctly (more-recent versions require less user input):

```python
train_dataset = nvt.Dataset(TRAIN_PATH, part_mem_fraction=GPU_MEMORY_FRAC)
valid_dataset = nvt.Dataset(VALID_PATH, part_mem_fraction=GPU_MEMORY_FRAC)
```

Note that we can also **force** iteration based processing by doing the following:

```python
proc.update_stats(train_dataset)
proc.write_to_dataset(PREPROCESS_DIR_TRAIN, train_dataset, apply_ops=True, shuffle=True, out_files_per_proc=2, iterate=True)
proc.write_to_dataset(PREPROCESS_DIR_VALID, valid_dataset, apply_ops=True, shuffle=False, out_files_per_proc=1, iterate=True)
```

I get the same results when I do this, so it probably makes sense to stick with the simpler `apply` API.

**Comment by rdipietro** [comment]
Thanks for the update.

I'm trying to confirm by reproducing, also using https://github.com/NVIDIA/NVTabular/pull/160, but am having trouble.

Did you make any other changes, aside from those to `nvt.Dataset`?

I'm getting the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-b7dfaee3926b> in <module>
----> 1 proc.apply(train_dataset, apply_offline=True, record_stats=True, output_path=PREPROCESS_DIR_TRAIN, shuffle=True, out_files_per_proc=2)
      2 proc.apply(valid_dataset, apply_offline=True, record_stats=False, output_path=PREPROCESS_DIR_VALID, shuffle=False)

/nvtabular/nvtabular/workflow.py in apply(self, dataset, apply_offline, record_stats, shuffle, output_path, output_format, out_files_per_proc, **kwargs)
    724                 shuffle=shuffle,
    725                 output_format=output_format,
--> 726                 out_files_per_proc=out_files_per_proc,
    727             )
    728         else:

/nvtabular/nvtabular/workflow.py in build_and_process_graph(self, dataset, end_phase, output_path, record_stats, shuffle, output_format, out_files_per_proc, apply_ops)
    810         if apply_ops:
    811             for idx, _ in enumerate(self.phases[:end]):
--> 812                 self.exec_phase(idx, record_stats=record_stats)
    813         if output_format:
    814             output_path = output_path or "./"

/nvtabular/nvtabular/workflow.py in exec_phase(self, phase_index, record_stats)
    630                 for r in dask.compute(stats, scheduler="synchronous")[0]:
    631                     computed_stats, op = r
--> 632                     op.finalize(computed_stats)
    633                     self._update_statistics(op)
    634                     op.clear()

/conda/envs/rapids/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvtabular/nvtabular/ops.py in finalize(self, dask_stats)
    265     @annotate("Moments_finalize", color="green", domain="nvt_python")
    266     def finalize(self, dask_stats):
--> 267         for col in dask_stats["count"].index.values_host:
    268             self.counts[col] = float(dask_stats["count"][col])
    269             self.means[col] = float(dask_stats["mean"][col])

AttributeError: 'StringIndex' object has no attribute 'values_host'
```

**Comment by rjzamora** [comment]
It looks like your cudf version is a bit too old - We recently started using `values_host` when cudf made it "ilegal" to iterate through the index (to avoid implicit device -> host transfers).  If you are on the latest cudf, then it is possible they made another change

**Comment by rdipietro** [comment]
Are you using 0.14.0? And if so, any specific minor version? I can try to use whatever you're using. This error was with cudf `0.14.0a+4291.g6bae03d40`

**Comment by rjzamora** [comment]
Ah right -  Sorry.  The latest version of nvtabular does require 0.15

**Comment by rdipietro** [comment]
Thanks – I'll try that
