### ISSUE TITLE
[OP] Join onto external dataframe, file, dictionary

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#17]
<a href="https://github.com/EvenOldridge"><img src="https://avatars1.githubusercontent.com/u/25941453?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EvenOldridge](https://github.com/EvenOldridge)**
_Thursday Mar 26, 2020 at 02:22 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/32_

----

**Is your operator request related to a problem? Please describe.**
Outbrains dataset

Join to external data in multiple formats.  This mechanism will also be used / shared by https://github.com/rapidsai/recsys/issues/31 to apply the groupby operations.

**Describe the solution you'd like**
 - Type: Feature Engineering
 - input column type(s): [Categorical]
 - input options:
   - Columns to join off of:  [Categorical] (just in case naming isn't the same?)
   - Categorical column names to be joined
   - Continuous column names to be joined
 - Expected transformation of the data after application: Data is joined 

**Optional: Describe operation stages in detail***
Statistics per chunk: N/A
Statistics combine: N/A
Apply: Join

Context:
Note that this is meant to be an iterator to gdf join and not an iterator to iterator join which we'll figure out in the future.

**Comment by rnyak** [comment]
Related cudf issue: https://github.com/rapidsai/cudf/issues/5621

**Comment by benfred** [comment]
We should pass in a nvtabular.Dataset to the operator - and merge with the groupby apply
