### ISSUE TITLE
[DOC] Maintain multiple versions of API docs

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#178]
The generated API documentation should be updated for each version, but we will want to host older versions of the docs online as well. As an example we should have the v0.1.1 docs up at https://nvidia.github.io/NVTabular/v0.1.1/index.html , the v0.2.0 docs up at https://nvidia.github.io/NVTabular/v0.2.0/index.html and the latest docs being pushed from the nightly build at https://nvidia.github.io/NVTabular/nightly/index.html

There are some sphinx extensions that ,ay help with this:
https://holzhaus.github.io/sphinx-multiversion/master/index.html
https://github.com/sphinx-contrib/sphinxcontrib-versioning

To get the nightly docs version going, we should hook into the CI system to automatically build and update the docs.

**Comment by jperez999** [comment]
On every PR commit... or after we merge each PR in or nightly?

**Comment by benfred** [comment]
> On every PR commit... or after we merge each PR in or nightly?

We only need to build docs nightly

**Comment by benfred** [comment]
#202 builds the docs for multiple versions, and adds a version picker to the sidebar on the docs.
