### ISSUE TITLE
[DOC]Is there a clear way to know how to run nvtabular?

### ISSUE THREAD

**Issue by l00213780** [NVIDIA/NVTabular#185]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by benfred** [comment]
Is there something not covered by our documentation? https://nvidia.github.io/NVTabular/  

I'd suggest looking at the example notebooks linked above there, let me know if you need anymore help on getting started!

**Comment by l00213780** [comment]
@benfred When I run the optimize_criteo.ipny，criteo-example.ipny notebook, I find some bugs that are not fixed on the nvtabular container.

**Comment by rnyak** [comment]
@l00213780 can you please share here the bugs you find? We need more information on that. Thanks.

**Comment by benfred** [comment]
@l00213780 Closing this - feel free to reopen if you have more information on what's not working
