### ISSUE TITLE
Categorify Op Improvements

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA/NVTabular#194]
Some additional requirements for the categorify op:
 - Ability to select a fixed cardinality embedding rather than a frequency limit (same options for low frequency; mapping to a single value and hashing)
 - quotient remainder hashing (for the entire set, for a frequency limit, or for a fixed cardinality embedding)

**Comment by alecgunny** [comment]
Related to #78 .

For the q/r hashing, it might make sense to add on to that implementation by adding a `hash_type` kwarg that takes `"quotient"` or`"remainder"` as possible values, that way users who want to do both can add 2 `Categorify` ops using a different value for that kwarg in each.

The problem with that, though, is that we would be `Categorify`-ing values _above_ the frequency threshold twice, which is a waste. The alternative would be to also accept a `"both"` argument or something to do both in the same op, but curious if we have the API support for the same `Op` to output 2 columns.

**Comment by EvenOldridge** [comment]
I think hash type should definitely be an input option.  There are a number of hashing mechanisms beyond this that we'll want to cover so making that part compartmentalized would be good.

**Comment by benfred** [comment]
Quotient remainder moved to https://github.com/NVIDIA/NVTabular/issues/573
