### ISSUE TITLE
[BUG] getting one more parquet files than given out_files_per_proc

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#211]
**Describe the bug**

I am working on criteo day_0.parquet file. I run the steps below:

```
...
proc = nvt.Workflow(
    cat_names=['C01', 'C02', 'C09'],
    cont_names=CONTINUOUS_COLUMNS,
    label_name=LABEL_COLUMNS)

proc.add_cont_feature([ZeroFill(), LogOp()])
proc.add_cont_preprocess(Normalize())

# categorification with frequency thresholding
proc.add_cat_preprocess(Categorify(freq_threshold=8))

proc.finalize()

train_dataset = nvt.Dataset(train_paths, engine='parquet', part_mem_fraction=0.12)
valid_dataset = nvt.Dataset(valid_paths, engine='parquet', part_mem_fraction=0.12)
proc.apply(train_dataset, shuffle=nvt.io.Shuffle.PER_PARTITION, output_path=output_train_dir, out_files_per_proc=3)
```

This generates four parquet files, of which one is 4 bytes size in the `output_path`.  Because of this file, I got `Parquet file size is 4 bytes, smaller than the minimum file footer (8 bytes)` error when training Keras model. I have to manually remove it to be able to run the model.

**Expected behavior**
Number of processed parquet files stored in the `output_path` should be equal to `out_files_per_proc` param value.

**Environment details (please complete the following information):**
 - Environment location: Conda
 - Method of NVTabular install: `Pip install -e`

**Comment by rnyak** [comment]
@rjzamora for viz.

**Comment by rjzamora** [comment]
@rnyak - Where you able to confirm that this is still a problem for you with the latest `main` branch?
