### ISSUE TITLE
[FEA] MultiGPU TensorFlow Dataloader

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#219]
Similar to https://github.com/NVIDIA/NVTabular/issues/57 ,  we should add the ability to the TF dataloader to train on multiple GPU's

**Comment by alecgunny** [comment]
I'll need to do more research into this, but my intuition is that this is probably nontrivial and might not be realistic to make it into 0.2

**Comment by benfred** [comment]
Moved to 0.3 - though it'd be great to verify if we can get this going with a similar mechanism to what we're doing with PT before then.

**Comment by jperez999** [comment]
@benfred Does this count as complete now that we have horovod?
