### ISSUE TITLE
[FEA] Support fast.ai v2

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#234]
Our existing notebooks don't work with [fast.ai v2](https://www.fast.ai/2020/08/21/fastai2-launch/) - and throws an error like ```ModuleNotFoundError: No module named 'fastai.basic_train'```.  We should update to work with the newer version of fast.ai

**Comment by bschifferer** [comment]
I investigates to update NVTabular's Rossmann example notebook for fast.ai v2.

Issue is, fast.ai v2 does not provide DataBunch as a class anymore. fast.ai v2 provides following examples for tabular data
https://github.com/fastai/fastai/blob/master/dev_nbs/course/lesson6-rossmann.ipynb
https://github.com/fastai/fastai/blob/master/dev_nbs/course/lesson4-tabular.ipynb

Using a 
`
to = TabularPandas(df, ...)
dls = to.dataloaders(bs=512, path=path)
` 
to create the data loaders.

Imports can be updated by

old
`
from fastai.tabular import TabularModel
from fastai.basic_train import Learner
from fastai.layers import MSELossFlat
from fastai.torch_core import flatten_check
from fastai.basic_data import DatasetType

`

new
`
from fastai.tabular.model import TabularModel
from fastai.tabular.learner import TabularLearner
from fastai.layers import MSELossFlat
from fastai.torch_core import flatten_check
#from fastai.basic_data import DatasetType was not used in NVTabular Rossmann example
`
