### ISSUE TITLE
[DOC] NVtabular docs

### ISSUE THREAD

**Issue by efrats** [NVIDIA/NVTabular#258]
## Report incorrect documentation
“accelerating-tensorflow.ipynb” under TF

https://github.com/NVIDIA/NVTabular/blob/main/examples/tensorflow/accelerating-tensorflow.ipynb

3 issues: 
1) In 6: all commented – is this how it should be?

2) “Putting Our Differences Aside” – duplicate of paragraph. 
3)  line after “This is an ugly little function…” - duplicate 
 
**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://github.com/NVIDIA/NVTabular/blob/main/examples/tensorflow/accelerating-tensorflow.ipynb

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by alecgunny** [comment]
1. Yes: the code is onerous from a time and memory standpoint, and so I'd rather leave it as "optional" so that users blindly clicking through the notebook don't accidentally use up hundreds of gigabytes of their memory. I'll make a note of that in the text above it.
2/3. Good catch, I'll fix

**Comment by benfred** [comment]
Thanks for pointing this out! This should be fixed by #267
