### ISSUE TITLE
[FEA] Move or remove get_emb_sz method on Categorify op

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#27]
<a href="https://github.com/alecgunny"><img src="https://avatars0.githubusercontent.com/u/14932242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alecgunny](https://github.com/alecgunny)**
_Wednesday May 13, 2020 at 16:53 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/121_

----

It's not entirely clear to me why `Categorify.get_emb_sz` and its associated helper methods are included as methods on the `Categorify` object, especially when nothing in the code actually uses attributes from the object itself (with the exception of the `self.embed_sz`, which gets set rather than read from):
```python
    def get_emb_sz(self, encoders, cat_names):
        work_in = {}
        for key in encoders.keys():
            work_in[key] = encoders[key] + 1
        # sorted key required to ensure same sort occurs for all values
        ret_list = [
            (n, self.def_emb_sz(work_in, n))
            for n in sorted(cat_names, key=lambda entry: entry.split("_")[0])
        ]
        return ret_list

    def emb_sz_rule(self, n_cat: int) -> int:
        return min(16, round(1.6 * n_cat ** 0.56))

    def def_emb_sz(self, classes, n, sz_dict=None):
        """Pick an embedding size for `n` depending on `classes` if not given in `sz_dict`.
        """
        sz_dict = sz_dict if sz_dict else {}
        n_cat = classes[n]
        sz = sz_dict.get(n, int(self.emb_sz_rule(n_cat)))  # rule of thumb
        self.embed_sz[n] = sz
        return n_cat, sz
```
While I'm personally of the opinion that it's not our library's job to be providing rules of thumb for building deep learning models, just to provide the data for whatever rules the user wants to use, if we're intent on having this function somewhere it seems like it would be better served as a standalone function of a single encoder or as a property of the encoder itself:
```python
emb_szs = [get_embed_sz(proc.stats["categories"][column]) for column in proc.columns_ctx["categorical"]["base"]]

# or
emb_szs = [proc.stats["categories"][column].embed_sz[1] for column in proc.columns_ctx["categorical"]["base"]]
```

**Comment by rdipietro** [comment]
Note that solutions like

```python
emb_szs = [get_embed_sz(proc.stats["categories"][column]) for column in proc.columns_ctx["categorical"]["base"]]
```

will break compatibility with `torch_dataloader` (and possibly other modules too), which sort columns (see for example [this line](https://github.com/NVIDIA/NVTabular/blob/2e5f90bc47c96292484f210a39016918038a6911/nvtabular/torch_dataloader.py#L128) in `create_tensors`).

@benfred @alecgunny is there any agreed upon convention for column ordering? I'm wondering why `torch_dataloader` reorders columns, and whether this is done elsewhere, too.

If reordering is necessary, then I'll create a new issue to order the `proc.stats["categories"]` dictionary (among others), since as of CPython 3.6 (and more officially Python 3.7 in general) dictionaries are sorted.

**Comment by rdipietro** [comment]
Just realized that this same logic is present in `get_emb_sz` itself. Is this sorting convention necessary or is it something we can get rid of?

**Comment by alecgunny** [comment]
@rdipietro I think this is kind of a distinct issue, though certainly one worth noting. My point with the snippet
```
emb_szs = [get_embed_sz(proc.stats["categories"][column]) for column in proc.columns_ctx["categorical"]["base"]]
```
was simply to show what the call signature (i.e. `get_embed_sz(...)`) looks like. How you choose to iterate through it in a list is up to you (though obviously a good implementation will match how our dataloader orders things, and makes more critical exposing the means by which our dataloader does that ordering), but won't change the underlying function call.

While I'm thinking about this, I think it's probably worth discussing the choice of the syntax `embed_sz`. I know it matches what FastAI uses, but as we begin to expand beyond it as the target use case, I think abandoning some of its more idiosyncratic usage of abbreviations is worth doing for the sake of clarity.

**Comment by benfred** [comment]
@rdipietro @alecgunny I've got a PR here that should fix this https://github.com/NVIDIA/NVTabular/pull/110 - it moves get_emb_sz to a separate function not associated with the Categorify op, renames to be consistent with other parts of the code (get_embedding_size) and consolidates the 'sort' code of the categorical names . Would appreciate if you could take a look at it
