### ISSUE TITLE
AttributeError: module 'nvtabular.io' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by ZacheryAU** [NVIDIA/NVTabular#300]
Hey there, 

I was running the command:
`python3 preprocess_nvt.py --src_csv_path=dcn_data/train/train.txt --dst_csv_path=dcn_data/train/ --normalize_dense=1 --feature_cross=0 --criteo_mode=0`
from [https://github.com/NVIDIA/HugeCTR/tree/master/samples/dcn](url)
and got the Attribute Error on the title. Could anyone help me?

More, the github page says 0.2 has been released, but according to the NGC page [http://ngc.nvidia.com/catalog/containers/nvidia:nvtabular](url), there is only 0.1 image, which I installed, and amended the code:
`docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_PTRACE nvcr.io/nvidia/nvtabular:0.2 /bin/bash`
from 0.2 to 0.1, and the code at the beginning ran in this container (mount HugeCTR with type bind). Is there anything wrong in my installation? Thx.

**Comment by benfred** [comment]
We're about to release 0.2 (which is whats up on the github main branch) - but we're just waiting on a couple last minute QA activities to finish up before we push the new container to NGC.   The dataset API has changed with NVTabular 0.2 which is why you're hitting this error.

You can either wait a couple of days for the 0.2 release, or you can install straight from this GH repo. You'll need to install cudf 0.15 (```conda install -c rapidsai -c nvidia -c numba -c conda-forge  cudf=0.15 python=3.6 cudatoolkit=10.2``` adjusting python version and cuda toolkit as appropiate) and then install NVTabular with  ```pip install git+https://github.com/NVIDIA/NVTabular.git``` .

**Comment by ZacheryAU** [comment]
> We're about to release 0.2 (which is whats up on the github main branch) - but we're just waiting on a couple last minute QA activities to finish up before we push the new container to NGC. The dataset API has changed with NVTabular 0.2 which is why you're hitting this error.
> 
> You can either wait a couple of days for the 0.2 release, or you can install straight from this GH repo. You'll need to install cudf 0.15 (`conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.15 python=3.6 cudatoolkit=10.2` adjusting python version and cuda toolkit as appropiate) and then install NVTabular with `pip install git+https://github.com/NVIDIA/NVTabular.git` .

When I just conda instal cudf, it says 'Solving environment: failed with initial frozen solve.', and stops at 'Solving environment'

**Comment by ZacheryAU** [comment]
Later I downloaded the tar.bz2 files of cudf and rmm (both are 0.15) from anaconda.org manually and installed them locally, but got another error: 'librmm.so: cannot open shared object file: No such file or directory'. 
Then I downloaded librmm and installed it, it showed 'libcudart.so.10.2: cannot open shared object file: No such file or directory'

**Comment by benfred** [comment]
What version of cuda are you using  (like what does nvidia-smi show) ? It's weird that it can't find libcudart 

One other method of installing is getting a rapids docker image (from https://hub.docker.com/r/rapidsai/rapidsai/tags ) and then layering nvtabular on top w/ pip.

**Comment by ZacheryAU** [comment]
10.2

> What version of cuda are you using (like what does nvidia-smi show) ? It's weird that it can't find libcudart
> 
> One other method of installing is getting a rapids docker image (from https://hub.docker.com/r/rapidsai/rapidsai/tags ) and then layering nvtabular on top w/ pip.

**Comment by benfred** [comment]
The 0.2 NVTabular container is up now - https://ngc.nvidia.com/catalog/containers/nvidia:nvtabular . Let me know if this works out for you,

**Comment by ZacheryAU** [comment]
Thanks. It seems solved.

**Comment by benfred** [comment]
Great!  I'm glad to know its working for you
