### ISSUE TITLE
[FEA] Support reading datasets from Avro files

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#314]
We should add support for reading from Avro datasets.

**Comment by albert17** [comment]
There is not dask_cudf support to read Avro files. I looked into implementing it using cudf and to avoid double work I asked in rapids channel if there are plans to add support in near future. Keith Kraus told me to create a FEA Request in GItHub: https://github.com/rapidsai/cudf/issues/6496

If they add support we can use it in a similar way that what we are doing with CSV. If they don't (or we don't want to wait) we can implement it in a similar way that we are doing with Parquet.

Waiting to see what rapids does.
