### ISSUE TITLE
[FEA] Include bucket range as category stat on HashBucket Op

### ISSUE THREAD

**Issue by alecgunny** [NVIDIA/NVTabular#316]
DL model training workflows that are agnostic to the preprocessing used to generate a particular categorical feature will need to be able to recover the vocabulary size in order to construct the embedding. For features generated using the `Categorify` op, this is not an issue, since that information is recorded in the `Workflow` stats, which can be exported after preprocessing and read back in at train time.

But that information isn't recorded for the `HashBucket` op, which means you need to write some sort of exception which can somehow check for how that feature was generated then access the `Workflow` which was used to generate it, which is overall just a terrible way to have to implement things.

However, if we record `range(num_buckets)` as a stat for the op and mimic the API used for recovering the `Categorify` categories, then we can use the stats as an input to the training script which can then recover all the necessary information in an agnostic fashion.

Related to #78, which will combine these functionalities. Any implementation there should include the indices we include for the hash bins as part of the category stats.

**Comment by EvenOldridge** [comment]
Ah, you beat me to it :-)  @benfred let's merge these tickets.  I want to make sure that all forms of categorical encoding are covered, but Alec's description is way more detailed than mine.
