### ISSUE TITLE
Installation nvtabular using conda on windows-64

### ISSUE THREAD

**Issue by AnshuTrivedi** [NVIDIA/NVTabular#318]
Issue: PackagesNotFoundError
Command used to install: conda install -c nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.6 cudatoolkit=10.2

System info: 
![Screenshot (106)](https://user-images.githubusercontent.com/47869948/94100858-3944c800-fe4c-11ea-81b2-30695be2f568.png)

Error log:
![Screenshot (108)](https://user-images.githubusercontent.com/47869948/94101163-fdf6c900-fe4c-11ea-9e9b-d4990253bc69.png)

Conda info:
 conda version : 4.8.5
 conda-build version : 3.18.11
 python version : 3.7.7.final.0
 virtual packages : __cuda=10.2
I also searched package on anaconda.org but couldn't find.There is nvtabular only for linux O.S.

**Comment by benfred** [comment]
@AnshuTrivedi  Right now NVTabular only runs on Linux =( We're built on top of cudf which doesn't have windows support yet (https://github.com/rapidsai/cudf/issues/28 ).
