### ISSUE TITLE
[DOC] README is only linux O.S oriented 

### ISSUE THREAD

**Issue by AnshuTrivedi** [NVIDIA/NVTabular#319]
## Report incorrect documentation
README doesn't mention commands or procedure of nvtabular installation for windows users.

**Describe the problems or issues found in the documentation**
I followed README for library installation using conda ,couldn't find package using conda on windows-64 system. See #318 .
Then i tried to install using docker on Windows-64 ,it downloaded image for  nvcr.io/nvidia/nvtabular:0.2. But failed in 2nd step using `source activate rapids`  on power shell.
![Screenshot (109)](https://user-images.githubusercontent.com/47869948/94139840-f274c380-fe87-11ea-8ec3-84a2109057f8.png)

**Steps taken to verify documentation is incorrect**
* Followed README to install nvtabular using docker on windows-64.
* Command used:  docker run --gpus all --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_PTRACE nvcr.io/nvidia/nvtabular:0.2 /bin/bash

**Suggested fix for documentation**
Please mention in README if libeary doesn't support Windows if does then link to nvtabular installation procedure.

**Steps taken to search for needed documentation**
List any steps you have taken:
* Googled about whether nvtabular supports Windows 
* Checked for rapids official site for windows comaptibility
https://rapids.ai/start.html

**Comment by benfred** [comment]
Thanks for raising this issue!
We should update the README to state that NVTabular only works on linux (because of our cudf dependency).

**Comment by AnshuTrivedi** [comment]
@benfred Well, I think I can update the README and raise an PR afterwards, what say?

**Comment by benfred** [comment]
we've updated the readme to say:
>NOTE: NVTabular will only run on Linux. Other operating systems are not currently supported.
