### ISSUE TITLE
[Task]Evaluate the RecSys 2020 challenge workflow and create github issues for all missing operators.

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#32]
<a href="https://github.com/EvenOldridge"><img src="https://avatars1.githubusercontent.com/u/25941453?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EvenOldridge](https://github.com/EvenOldridge)**
_Friday May 15, 2020 at 20:41 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/142_

----

**What needs doing**
Evaluate the RecSys 2020 challenge workflow and create github issues for all missing operators.
Issues should be under the nvTabular project and a part of the RecSys 2020 workflow milestone as this issue is.

Please create a new tab and add operators to  both the workflow to operator master doc and the master operator doc.  Please validate with the code in the source repo to ensure nothing is missing. 

**Additional context**

Master operator doc:
https://docs.google.com/spreadsheets/d/1irirSo70PvuCovb_0nnJNjWUpSGhbjDOl72kxS_8fRk/edit#gid=1173451941

Workflow to operator master doc:
https://docs.google.com/spreadsheets/d/1EcY9n3uEUs3pPl7auEE4ahNQfjafaMTl6R-Zvk-7XlE/edit#gid=796720992

Source repo:
https://github.com/rapidsai/recsysChallenge2020/

**Comment by EvenOldridge** [comment]
This is complete
