### ISSUE TITLE
[QST] Does NVTabular support commercial GPUs.

### ISSUE THREAD

**Issue by quocdat32461997** [NVIDIA/NVTabular#321]
I wonder if NVTabular supports commerical GPUs e.g. RTX 3080 or older. As NVTabular is built on top of RAPIDS, NVTabular could be used on these GPUS but I am not sure. Thanks for your time.

**Comment by benfred** [comment]
We do support commercial gpu's - I have run NVTabular successfully on a 1080Ti for instance.    We should work fine on all Pascal and newer gpu's (we've tested on P100/V100/A100).

**Comment by quocdat32461997** [comment]
Thanks
