### ISSUE TITLE
[BUG] LambdaOps for filtering causing issues with column names

### ISSUE THREAD

**Issue by alecgunny** [NVIDIA/NVTabular#328]
Take the following example:
```
import nvtabular as nvt
import cudf
import numpy as np

workflow = nvt.Workflow(cat_names=["cat"], cont_names=["cont"], label_name=["label"])
workflow.add_feature(nvt.ops.LambdaOp("drop_bads", lambda col, gdf: col[gdf["label"] != -1], replace=True))
workflow.add_cont_preprocess(nvt.ops.Normalize())
workflow.add_cat_preprocess(nvt.ops.Categorify())

ids = np.random.choice(np.arange(10000, 999999), size=500, replace=False)
df = cudf.DataFrame({
    "cat": np.random.choice(ids, size=10000),
    "cont": np.random.randn(10000),
    "label": np.random.randint(-1, 2, size=10000)
})
dataset = nvt.Dataset(df)
workflow.apply(dataset)
```
This will create a `KeyError` when application of the `Normalize` op tries to find the column `"cont"`. Where did it go? Well, the "drop_bads" `LambdaOp` filtered some elements out, which meant that [this line](https://github.com/NVIDIA/NVTabular/blob/679b315bf4ec7551460a497a51595acaae118ad0/nvtabular/ops/transform_operator.py#L88) got triggered to return the `new_gdf` even though `replace=True`. But because `replace=True`, the wrong column information got forwarded to `Normalize` about what columns to expect.

Implementing a dedicated filtering op would probably be useful in general, but in the shorter term functionality like this might be achieved by either
- allowing the user to provide a `None` name to the LambdaOp, in which case it always operates in-place and returns the transformed dataframe
- adding some sort of flag that gets passed to `assemble_new_df` to indicate that *all* features are being operated on and so there's no need to perform this check (replace the column names and hand back the transformed dataframe)

We could also just explicitly exclude lambda functions that change the number of rows in a data frame, but in that case it's worth putting this shape check in `LambdaOp.op_logic` and raising an error there so that users are aware of what's going on.

**Comment by benfred** [comment]
Have you checked out the filter op yet? https://nvidia.github.io/NVTabular/main/api/ops/filter.html

**Comment by alecgunny** [comment]
Oh wow how'd I miss that, thanks Ben. Trying to think if there are other use cases where the LambdaOp might be used to reduce the number of rows that aren't covered by Filter, but can't really come up with anything. Would adding a shape check at the end of `LambdaOp.op_logic` and then raising an error or a warning if the shape is wrong and `replace=True` be useful just from a future-proofing standpoint?

**Comment by benfred** [comment]
This isn't an issue anymore afaict -
