### ISSUE TITLE
[QST] Same models?

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/NVTabular#352]
**What is your question?**
I am looking these two examples for an apple to apple comparison: [example1](https://github.com/NVIDIA/NVTabular/tree/main/examples/hugectr) and [example2](https://github.com/NVIDIA/NVTabular/tree/main/examples/tensorflow). Are they using exactly the same model with the exact same parameters? I see they are both DLRM but I am seeing some parameter differences

**Comment by ethem-kinginthenorth** [comment]
I believe I have mapped some parameters. Further, hugectr example needs another dense layer to match embedding size. Hoping this would do the trick

**Comment by albert17** [comment]
HugeCTR example is being updated. 

You can see the original HugeCTR samples for DLRM here: https://github.com/NVIDIA/HugeCTR/tree/master/samples/dlrm
