### ISSUE TITLE
[QST] How to get the latest release from conda?

### ISSUE THREAD

**Issue by abditag2** [NVIDIA/NVTabular#362]
I install nvtabular using the install command on the readme page, version 0.11 of nvtabular is installed. What is the best way to install the latest release?

I used this command: 
`conda install -c nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.6 cudatoolkit=10.2`

**Comment by rnyak** [comment]
@abditag2 you can first install rapidsai into a conda env using conda command (see https://rapids.ai/start.html). Then run `pip install git+https://github.com/NVIDIA/NVTabular.git`.  Note that, we recommend installing either cuDF 0.15 (stable) or 0.16 (nightly).

You can also use NVTabular beta release (0.2) container. See https://github.com/NVIDIA/NVTabular#getting-started for the docker command.

**Comment by abditag2** [comment]
Thanks for the response. I was able to install it using 
    `conda install -c nvidia/label/nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.7 cudatoolkit=10.2`
