### ISSUE TITLE
[FEA] Simplify API for adding ops to a workflow

### ISSUE THREAD

**Issue by rjzamora** [NVIDIA/NVTabular#383]
**Is your feature request related to a problem? Please describe.**
After a few offline discussions (and my own personal experience), I feel that the current `add_preproc`/`add_feature` API is  causing unnecessary confusion for new users.   For example, it seems a bit confusing that `add_preprocess` **should** be used to add `DFOperator`s (which have 1+ `StatOperator` dependencies), **unless* those ops are transforming columns that do not exist in the raw dataset.  Overall, I don’t think there is a real need for two different APIs at all.

I suggest we consolidate the API to a single `add_operators` (or something like that), and deprecate the existing API in a future release.

**Describe the solution you'd like**
A consolidated API for adding **all** operator types (like `add_operators`).  Operator-dependencies can still be captured by adding a `list` of ops as a single pipeline.

**Describe alternatives you've considered**
The obvious alternative is to carry on with the existing API.  This is fine, but likley to cause confusion for new users.

**Comment by benfred** [comment]
This should be handled by the API overhaul (#472)

**Comment by benfred** [comment]
New API is merged ! We no longer have add_preprocess / add_feature anymore
