### ISSUE TITLE
[BUG] record_stats=False not working as expected

### ISSUE THREAD

**Issue by meprem** [NVIDIA/NVTabular#386]
**Describe the bug**
record_stats=False corrupts validation dataset. However, it works fine, when I set record_stats=True on the validation dataset.
**Steps/Code to reproduce bug**

Workflow Processor:
![workflow_processor](https://user-images.githubusercontent.com/9160634/97654276-cd8fe500-1a1f-11eb-8972-4e7a0323898e.png)

- Train dataset record_stats=True and Validation dataset record_stats=False -> as you can see CumCount Max is 896 instead of 299.

![1_train_true_valid_false](https://user-images.githubusercontent.com/9160634/97654269-cb2d8b00-1a1f-11eb-905b-fa9502031469.png)

- Train dataset record_stats=True and Validation dataset record_stats=True -> as you can see CumCount Max is now  299.
![2_train_true_valid_true](https://user-images.githubusercontent.com/9160634/97654275-ccf74e80-1a1f-11eb-92fa-a231b5adb058.png)

**Expected behavior**
I am expecting this output when Validation dataset record_stats is set to False.

![2_train_true_valid_true](https://user-images.githubusercontent.com/9160634/97654275-ccf74e80-1a1f-11eb-92fa-a231b5adb058.png)

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

Installed 0.2 version from here...https://pypi.org/project/nvtabular/ 

And using it with Rapids 0.16 as I need pivot().
 

**Additional context**

**Comment by rjzamora** [comment]
Thanks for raising an issue @meprem - I haven't reproduced the problem yet, so it may be difficult to track down the cause.  **Is there any way you can share a simple/example dataset that can reproduce the problem?**

Note that I tried running through your general workflow, but the following dataset didn't lead to any corruption:
```python
from dask.datasets import timeseries

ddf = timeseries().reset_index(drop=True)
train_dataset = nvt.Dataset(ddf.partitions[:-5])
valid_dataset = nvt.Dataset(ddf.partitions[-5:])
```

**Comment by meprem** [comment]
![bug](https://user-images.githubusercontent.com/9160634/97923193-74bb9780-1d12-11eb-99c3-9c506b5d12b2.png)

**Comment by rjzamora** [comment]
I see - Thanks for the simple reproducer!

In the example above (for the case where all values are transformed to `0`), you are using your training data to find all unique categories for the `Categorify` transformation, but performing the encoding on the validation data.  Since your validation data does not include any of the same values as your training data (for the `"key"` column), all values are encoded to `0` (the catch-all for null and unknown encodings).  In other words, the behavior seems correct to me.

Please do let me know if I am misunderstanding the problem, or if you think a different behavior would make more sense.

**Comment by meprem** [comment]
Thank you for the explanation. It makes sense. I just wanted to pass down 'key' as it is since it's the id for my time-series data.

I end up adding

proc.add_feature(
    nvt.ops.LambdaOp(
      op_name='id',
      f = lambda col, gdf: col,
      columns=['key'],
     replace=False
  )
)


And later in the code after second proc.apply():

df['key'] = df['key_id']
df = df.drop(columns=['key_id']


That's said, is there a better way to pass down id column untouched via NVTabular. For tabular data it doesn't matter but for time-series it does...something like NoOp.

Thank you.

**Comment by rjzamora** [comment]
>is there a better way to pass down id column untouched via NVTabular

Rather than allowing the `Categorify` to act on **all** categorical columns (the default), you can specify a subset with `Categorify(columns=<your-list>)`.

**Comment by rjzamora** [comment]
Perhaps it would be reasonable to add a `Workflow` parameter to specify a list of columns that should pass through NVTabular unchanged - Thoughts on this @benfred ?  I'm honestly unsure how often a feature like this would be used.

**Comment by benfred** [comment]
We've changed the API  (with #472) - so that its pretty easy to pass through columns unchanged to the output .
