### ISSUE TITLE
[BUG] GroupByMoments requires cont_names and has to be a list

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#40]
<a href="https://github.com/bschifferer"><img src="https://avatars0.githubusercontent.com/u/19567274?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bschifferer](https://github.com/bschifferer)**
_Wednesday May 20, 2020 at 14:35 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/152_

----

The doc string of GroupByMoments is not aligned with the functionality of the operator:
1. If I use "count" as only stats, then there is no need to define cont_names. In that case, there will be an error
2. The doc string defines, that cont_names can be a string. In the case that cont_names is a single column as a string, then there is an error

Steps to reproduce
```
import cudf as gd
import pandas as pd
import nvtabular as nvt
from nvtabular.ops import Normalize, FillMissing, Categorify, Moments, Median, Encoder, LogOp, ZeroFill, GroupByMoments
from nvtabular.ops import *

cat_1 = np.asarray(['a']*12 + ['b']*10 + ['c']*10)
num_1 = np.asarray([1,1,2,2,2,1,1,5,4,4,4,4, 1,2,3,4,5,6,7,8,9,10, 1,2,3,4,5,6,7,8,9,10])
pdf_1 = pd.DataFrame({'cat': cat_1, 'num': num_1})

gdf = cudf.from_pandas(pdf_1)

proc = nvt.Workflow(cat_names=['cat'], cont_names=['num'], label_name=[])
proc.finalize()

# First bug
gm = GroupByMoments(
    cat_names='cat',
    stats=['count']
)
gm.apply_op(gdf, columns_ctx=proc.columns_ctx, input_cols='all', target_cols=['base'])
gm.read_fin()
#TypeError: only integer scalar arrays can be converted to a scalar index

# Second bug
gm = GroupByMoments(
    cat_names='cat',
    cont_names='num',
    stats=['count']
)
gm.apply_op(gdf, columns_ctx=proc.columns_ctx, input_cols='all', target_cols=['base'])
gm.read_fin()
#AttributeError: 'str' object has no attribute 'copy'

# This works
gm = GroupByMoments(
    cat_names='cat',
    cont_names=['num'],
    stats=['count']
)
gm.apply_op(gdf, columns_ctx=proc.columns_ctx, input_cols='all', target_cols=['base'])
gm.read_fin()
```

**Comment by rjzamora** [comment]
I believe these bugs are addressed in `CategoryStatistics`, so I'll close this - Feel free to reopen with new details if there are still problems.
