### ISSUE TITLE
[BUG] Target Encoding Key Error

### ISSUE THREAD

**Issue by meprem** [NVIDIA/NVTabular#401]
**Describe the bug**
Please check the attached screenshot.

**Steps/Code to reproduce bug**
Please check the attached screenshot.

**Expected behavior**
Target Encoding fails to find the target column.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 Installed from source today.

**Additional context**
![target_encoding_key_error](https://user-images.githubusercontent.com/9160634/98148449-c6366480-1e81-11eb-9a11-4a38bb557ecd.png)

**Comment by benfred** [comment]
I think the problem here is running both Categorify and TargetEncoding in the same workflow. They both have dependencies on the GroupByStatistics operator to calculate statistics, and I think our workflow object is breaking right now because of this.
