### ISSUE TITLE
[DOC] Need some updates on API documents

### ISSUE THREAD

**Issue by PerkzZheng** [NVIDIA/NVTabular#407]
## Report incorrect documentation

**Location of incorrect documentation**
https://nvidia.github.io/NVTabular/main/api/ops/filter.html
It gives the example: 
```python
op = Filter(lambda df: df["a"] >=0)
```

**Describe the problems or issues found in the documentation**
Leads to errors : `TypeError: ddf type not supported.`

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
it should be:
```python
op = Filter(lambda df: df[df["a"] >=0])
```
---

I think NVTabular needs to update the API Document as the latest version. There could be more points like what I have shown above.

**Comment by alecgunny** [comment]
@benfred I know we've talked about replacing this behavior to check for a boolean and do the masking implicitly, has this been added?

**Comment by benfred** [comment]
We've fixed this in https://github.com/NVIDIA/NVTabular/pull/329/files - @PerkzZheng are you running the latest code ? If so can post a code snippet that reproduces this problem ?

**Comment by PerkzZheng** [comment]
@benfred I am running with the NGC docker (NVTabular 0.2).
```shell
docker pull nvcr.io/nvidia/nvtabular:0.2
```

Maybe I need to update to the latest inside the container.

**Comment by benfred** [comment]
thanks for confirming @PerkzZheng !
