### ISSUE TITLE
[Task] Merge GroupBy and Encoder

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#42]
<a href="https://github.com/oyilmaz-nvidia"><img src="https://avatars2.githubusercontent.com/u/35306097?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oyilmaz-nvidia](https://github.com/oyilmaz-nvidia)**
_Wednesday May 20, 2020 at 16:48 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/154_

----

GroupBy and Encoder are doing very similar operations including groupby function. When we run these two in a workflow, we do redundant operations.

We need to find a way to make a one groupby function call for both GroupBy and Encoder (or Categorify) object for efficiency.

**Comment by benfred** [comment]
@rjzamora Is there anything more to do on this - or can we mark this as done?

**Comment by rjzamora** [comment]
> @rjzamora Is there anything more to do on this - or can we mark this as done?

We have technically addressed the goal to align the code used by `GroupbyMoments` and `Encoder`. However, I think we may be able to take things a step further and completely remove the `Encoder` op (it is just a special case of `GroupbyMoments` anyway).
