### ISSUE TITLE
[BUG] Missing "nvtx" library in Criteo HugeCTR example 

### ISSUE THREAD

**Issue by AshishSardana** [NVIDIA/NVTabular#420]
**Describe the bug**
The Criteo HugeCTR example builds a new docker image on top of Rapids, installs NVTabular using pip and HugeCTR.
While running the first cell of criteo-hugectr.ipynb, encountered import errors for NVTX.

**Steps/Code to reproduce bug**

`bash examples/hugectr/docker/create_container.sh`
`docker run --runtime=nvidia --rm -it 
    -p 9999:8888 -p 9797:8787 -p 9796:8786 
    hugectr_rel /bin/bash`

Open python shell and import nvtabular:
`python`
`import nvtabular`

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rapids/notebooks/nvtabular/nvtabular/__init__.py", line 18, in <module>
    from . import io, workflow  # noqa
  File "/rapids/notebooks/nvtabular/nvtabular/workflow.py", line 30, in <module>
    from nvtabular.ops import DFOperator, StatOperator, TransformOperator
  File "/rapids/notebooks/nvtabular/nvtabular/ops/__init__.py", line 22, in <module>
    from .difference_lag import DifferenceLag
  File "/rapids/notebooks/nvtabular/nvtabular/ops/difference_lag.py", line 17, in <module>
    from nvtx import annotate
ModuleNotFoundError: No module named 'nvtx'
```

**Expected behavior**
Successful import of nvtabular

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of NVTabular install: From source

**Comment by rnyak** [comment]
@AshishSardana thanks for reporting that. If you install nvtx `conda install -c conda-forge nvtx` (most likely you have already tried), that should be solved.

**Comment by AshishSardana** [comment]
Yes, installing nvtx via conda solves it. I'd suggest that to be added in [Dockerfile.hugectr](https://github.com/NVIDIA/NVTabular/blob/main/examples/hugectr/docker/Dockerfile.hugectr).
Closing this issue!
