### ISSUE TITLE
[BUG] NVTabular Binary output has duplicate file name and can not hit target auc

### ISSUE THREAD

**Issue by shijieliu** [NVIDIA/NVTabular#433]
Hi, the HugeCTR team is doing internal QA now. And when trying to use binary output processed by NVT, we found 2 abnormal things.
1. duplicate file names in _file_list.txt like blow.
```
./criteo_bin/train/0.data
./criteo_bin/train/1.data
./criteo_bin/train/2.data
./criteo_bin/train/3.data
./criteo_bin/train/4.data
./criteo_bin/train/5.data
./criteo_bin/train/6.data
./criteo_bin/train/7.data
./criteo_bin/train/0.data
./criteo_bin/train/1.data
./criteo_bin/train/2.data
./criteo_bin/train/3.data
./criteo_bin/train/4.data
./criteo_bin/train/5.data
./criteo_bin/train/6.data
./criteo_bin/train/7.data
./criteo_bin/train/0.data
./criteo_bin/train/1.data
./criteo_bin/train/2.data
./criteo_bin/train/3.data
./criteo_bin/train/4.data
./criteo_bin/train/5.data
./criteo_bin/train/6.data
./criteo_bin/train/7.data
./criteo_bin/train/0.data
./criteo_bin/train/1.data
./criteo_bin/train/2.data
./criteo_bin/train/3.data
./criteo_bin/train/4.data
./criteo_bin/train/5.data
./criteo_bin/train/6.data
./criteo_bin/train/7.data

```
2. the auc drop during training compared with same input with norm format.
* [Wdl_bin.json](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.g585vu2hsi10)
* [dcn_bin.json](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.uksj4ird9so8)
* [Deepfm_bin.json](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.gff7ppt5cms)
* [criteo_bin.json](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.ibhobamikii1)

## steps to reproduce ##
1. we are using [wdl](https://gitlab-master.nvidia.com/zehuanw/hugectr/-/tree/master/samples/wdl#preprocessing-by-nvtabular), [dcn](https://gitlab-master.nvidia.com/zehuanw/hugectr/-/tree/master/samples/dcn#preprocessing-by-nvtabular), [deepfm](https://gitlab-master.nvidia.com/zehuanw/hugectr/-/tree/master/samples/deepfm#preprocessing-by-nvtabular), [criteo](https://gitlab-master.nvidia.com/zehuanw/hugectr/-/tree/master/samples/criteo#preprocessing-by-nvtabular)

**Comment by albert17** [comment]
We are having the collisions because of not generating unique filenames when using multiple nodes/GPUs: https://github.com/NVIDIA/NVTabular/blob/main/nvtabular/io/hugectr.py#L26. We need to update it to do it in the same way than we do in Parquet.
