### ISSUE TITLE
[BUG]using HugeCTR  with parquet format data generated by NVT has low auc(even less than 0.5) compared with the same input using normal format.

### ISSUE THREAD

**Issue by shijieliu** [NVIDIA/NVTabular#434]
Hi, HugeCTR team is doing internal QA and when testing hugectr with parquet format data generated by NVT has low auc(even less than 0.5) compared with the same input using normal format.
* [A100 log](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.jmnq8to1z2b3)
* [DGX2 log](https://docs.google.com/document/d/1Ht2mrEODktYh7C6CuDJ-3QJecfZkme2zQTzQosWiCgk/edit#heading=h.o00uw3uoix0)

## steps to reproduce
follow [criteo_parquet](https://gitlab-master.nvidia.com/zehuanw/hugectr/-/tree/master/samples/criteo#preprocessing-by-nvtabular)

not sure if this is related with https://github.com/NVIDIA/NVTabular/issues/402

**Comment by benfred** [comment]
possibly related to #396
