### ISSUE TITLE
[FEA] Support writing datasets to S3/GCS

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#487]
We can read datasets from S3/GCS using fsspec - but writing out doesn't currently work.

We should add support for this by opening files using fsspec , and passing those file objects to the cudf ParquetWriter.

We should also investigate whats needed to write out hugectr binary files to s3/gcs - but this is much lower priority.

**Comment by albert17** [comment]
After talking with Ayush Dattagupta, this should be already supported by ParquetWriter, so just passing the normal path should work. 

I have tested in both in GCS and S3 and it works successfully.

We will have to figure this out for HugeCTR formats for v0.5

**Comment by albert17** [comment]
It is not working properly. It is supported by read_parquet/to_parquet, but not by ParquetWriter
