### ISSUE TITLE
Rossmann example: end to end accuracy 

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/NVTabular#5]
In continuation of https://github.com/rapidsai/recsys/issues/75

This has bugged me for a long long long time now, and finally I've made some progress:

Known SOTA, i.e Kaggle top 10 LB is 0.108 (RMSPE).
Now NVTabular+fastai pipeline can match this SOTA.

1. fastai data -> fastai preproc -> fastai tabular model:
 epoch 	train_loss 	valid_loss 	exp_rmspe 	time
0 	0.009749 	0.014706 	0.118227 	00:17
1 	0.009324 	0.012835 	0.112409 	00:17
2 	0.008561 	0.012784 	0.110864 	00:17
3 	0.007877 	0.012329 	0.109368 	00:17
4 	0.007448 	0.012266 	0.109173 	00:17

2. fastai data -> nvtab preproc -> back to pandas -> fastai tabular model:
 epoch 	train_loss 	valid_loss 	exp_rmspe 	time
0 	0.066737 	0.049522 	0.206644 	00:18
1 	0.018532 	0.016543 	0.132428 	00:18
2 	0.012569 	0.014468 	0.120802 	00:18
3 	0.010587 	0.012440 	0.110982 	00:18
4 	0.008863 	0.011744 	0.108335 	00:19

3. fastai data -> nvtab preproc -> fastai tabular model:
epoch 	train_loss 	valid_loss 	my_exp_rmspe 	time
0 	0.011587 	0.012796 	0.119197 	00:12
1 	0.011569 	0.013420 	0.115161 	00:12
2 	0.009520 	0.011074 	0.106952 	00:12
3 	0.007833 	0.011341 	0.105943 	00:12
4 	0.006971 	0.010858 	0.104360 	00:12

there's some thing funny re. data ordering, and in case (3), shuffling data lead to SOTA results

proc.apply(train_ds_iterator, apply_offline=True, record_stats=True, output_path=PREPROCESS_DIR_TRAIN, shuffle=True, num_out_files=3)
proc.apply(valid_ds_iterator, apply_offline=True, record_stats=False, output_path=PREPROCESS_DIR_VALID, shuffle=True, num_out_files=3)

you can see my notebooks at /mnt/dldata/nvtabular-notebook-share

**Comment by vinhngx** [comment]
https://github.com/NVIDIA/NVTabular/pull/6

**Comment by rdipietro** [comment]
See https://github.com/NVIDIA/NVTabular/pull/9#issuecomment-652037945 for additional information on this issue
