### ISSUE TITLE
[QST] Migration from TF 1.x Dataset to NVTabular

### ISSUE THREAD

**Issue by eggie5** [NVIDIA/NVTabular#514]
I've got a TF v1.15 `Estimator`s project (ie not keras v2.x) w/ a `tf.data.Dataset` pipeline in place. The `Estimator` is a ranker using many categorical user feedback features that are embedded, so in other words it's a recsys. I feel like the pipeline is optimized as much as possible w/o exploring options outside of TF. 

During single-GPU training, I can max out a K80 GPU, but it's very jumpy, not saturated. For V100, I can only get usage up to ~30%. Looking to get more performance out of my pipeline, thus exploring NVTabular. 

My training routine (`tf.data.Dataset` Pipeline) reads tfrecords from disk, parses the ProtoBufs and batches the tensors.

What would be the first step in exploring NVTabular w/ a TF `Dataset`?

**Comment by EvenOldridge** [comment]
Hey Alex, we unfortunately require TF 2.2+ for the dlpack support which is necessary to pass data between cuDF and TF.  It should be possible to follow the same dataloading paradigm we developed to write a dataloader that's compatible with TF v1.x but it's not a part of our development path right now.
