### ISSUE TITLE
[FEA] apply joint TE on multiple columns after another op

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#522]
**Is your feature request related to a problem? Please describe.**
We'd like to the the following pipeline with LambdaOp and Target Encoding. 

```
unixReviewTime = ColumnGroup(['unixReviewTime'])
unixReviewTime_toDatetime = unixReviewTime >> (lambda col: cudf.to_datetime(col, unit='s')) >> Rename(postfix="_toDatetime")
unixReviewTime_toDatetime_year = unixReviewTime_toDatetime >> (lambda col: col.dt.year) >> Rename(postfix="_year")

columns_1 = [[['userID'] + unixReviewTime_toDatetime_year]]
te_features = columns_1 >> nvt.ops.TargetEncoding("label", kfold=1, p_smooth=20)
```
However this does not work. 

We also tried `columns_1 = ColumnGroup(['user_id']) +  unixReviewTime_toDatetime_year` but this is not providing us with the joint multi-column TE as we want.

**Describe the solution you'd like**
We want to be able to do  joint multi-column TE on `userID` (from the input dataset) and `unixReviewTime_toDatetime_year` that is calculated from a lambda op. So our final output column should be `TE_userID_unixReviewTime_toDatetime_year_label`.

**Additional context**
We are using new api and conda environment with the latest NVT main branch.

**Comment by benfred** [comment]
@rnyak #525 fixes - though note that the syntax will be

```python
te_features = [unixReviewTime_toDatetime_year + "userID"] >> nvt.ops.TargetEncoding("label", kfold=1, p_smooth=20)
```

instead of what you have listed above
