### ISSUE TITLE
[BUG] tritonclient package causes errors in NVT  

### ISSUE THREAD

**Issue by jperez999** [NVIDIA/NVTabular#616]
After installing the python tritonclient package using the following: `pip install nvidia-pyindex; pip install tritonclient[all]` nvtabular tests no longer succeed failing with NVRTC COMPILATION FAILURES in cudf sub libraries. See below for example failure:
```/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/frame.py:2486: in isnull
    return self.__class__._from_table(Frame(data, self._index))
cudf/_lib/table.pyx:44: in cudf._lib.table.Table.__init__
    ???
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column_accessor.py:59: in __init__
    self._data = OrderedColumnDict(data)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/frame.py:2484: in <genexpr>
    data_columns = (col.isnull() for col in self._columns)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py:746: in isnull
    result = result | libcudf.unary.is_nan(self)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py:1133: in __or__
    return self.binary_operator("or", other)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py:119: in binary_operator
    return _numeric_column_binop(
/opt/conda/envs/rapids/lib/python3.8/contextlib.py:75: in inner
    return func(*args, **kwds)
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py:679: in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
cudf/_lib/binaryop.pyx:209: in cudf._lib.binaryop.binaryop
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: NVRTC error: NVRTC_ERROR_COMPILATION

cudf/_lib/binaryop.pyx:107: RuntimeError
```
This happens on 80+ unit tests. 
This is currently blocking certification of both the inference and training containers.

**Comment by jperez999** [comment]
This also happens if you try to install tritonclient[http] (instead of [all])

**Comment by rnyak** [comment]
@benfred to reproduce the `request` error we get for `movielens_nvt` model, please follow these steps:

go to https://drive.google.com/drive/folders/1Y_to5n-pkh0N0BbYC20y0azPMIq03jWs to download the notebook and the `client_nvt.py`.

1. Create a folder `model` and subfolder `data` inside. Navigate to this `model` folder to mount this to `model` folder inside the container. You can add `client_nvt.py` file inside the `model` folder on your host.

2. Pull docker container and mount the folder to container

```
cd model
docker run --gpus=all -it -v ${PWD}:/model/ -p 9999:8888 -p 9797:8787 -p 9796:8786 --ipc=host --cap-add SYS_PTRACE gitlab-master.nvidia.com:5005/rapidsdl/dlfw_nvt/nvt_ctr:latest
```
3.  source activate rapids

4. Pull Onur's PR and use his branch `fea-hugectr-ensemble`

https://github.com/NVIDIA/NVTabular/pull/605


5. Start jupyter lab (install jupyter lab if necessary):

```
cd /nvtabular/examples/
jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''
```

6. Upload and Run the `movielens_hugectr_nvt.ipynb` notebook in the `/nvtabular/examples` directory and generate the processed parquet files. They will be saved to `/model/data` folder.

At this step in the notebook, we save the `movielens_nvt` model into a folder in the `/model/` directory. 


7. Pull HugeCTR triton server container and mount all the files in the `/model` directory to `/model` directory in the container. 

```
cd model

docker run --gpus=all -it -p 8005:8000 -p 8004:8001 -p 8003:8002 -v ${PWD}:/model/ gitlab-master.nvidia.com:5005/rapidsdl/dlfw_nvt/tri_nvt:latest
```
 
 8. Start triton server:

```
source activate rapids

tritonserver --model-repository /model/hugectr_models/
```
9. Send request to server: 

Use the first `nvt_ctr` container as client.  Run the command inside docker container:

`python client_nvt.py`
