### ISSUE TITLE
[BUG] Removing label columns for NVTabular Model for Triton Inference fails

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA/NVTabular#631]
**Describe the bug**
Creating a NVTabular model for Triton Inference fails, if I want to remove a column name which is only available in the input OR output workflow.
```
from nvtabular.inference.triton import export_tensorflow_ensemble
export_tensorflow_ensemble(model, workflow, modelname, path, outputcolumns)
```

The reason is, that we remove the columname from the input AND output dtypes. 
```
     68     for label in to_remove:
     69         del workflow.input_dtypes[label]
     70         del workflow.output_dtypes[label]
```
If the NVTabular workflow renames the label column, then the new column name is only available in the output and not in the input. (Same is true for the opposite, that the input column name is not available in the output_dtypes).

**Expected behavior**
Either, we should check, if column name is available in the input_dtypes / output_dtypes before deleting the column
OR, we have two separate parameter for deleting the columns - one for input and one for output - this fix would include that I may want to exlude only the column name from input but not from output (or the other way around)

**Comment by benfred** [comment]
Fixed by #632
