### ISSUE TITLE
[FEA] Add parquet file format support into hugectr writer

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#65]
<a href="https://github.com/oyilmaz-nvidia"><img src="https://avatars2.githubusercontent.com/u/35306097?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oyilmaz-nvidia](https://github.com/oyilmaz-nvidia)**
_Monday Jun 01, 2020 at 15:38 GMT_
_Originally opened as https://github.com/rapidsai/recsys/issues/189_

----

Parquet file format option should be added into hugectr class in io.py file. Hugectr support only binary file format right now and parquet will be added as a second format option.

Hugectr is expecting a metadata like number of rows in the file and this info is not added into parquet file by the cudf. As a workaround, we'll write this meta data into a separate file for now. Once the cudf updates the parquet writer, we'll also update the nvtabular side.

Please contact me for details.

**Comment by quocdat32461997** [comment]
Hi, 
I am trying to leverage HugeCTR for Recommendation model. As of now HugeCTR supports binary format; hence; until HugeCTR supports parquet; what should I go around this problem?
