### ISSUE TITLE
[FEA] Triton Integration Tests

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#653]
We need integration tests that work with Triton Inference Server.

We should be testing out the movielens inference notebooks, with generating models and export these models to triton. We should test out that Triton can start serving these models, and we can call them successfully over GRPC etc and get results that match the the DL model locally.

We should be testing out both the TensorFlow and HugeCTR inference solutions, as well as PyTorch once its available.

**Comment by oyilmaz-nvidia** [comment]
https://github.com/NVIDIA/NVTabular/pull/673
