### ISSUE TITLE
[Task] Add a unit test to check the accuracy of the models after deployed for inference

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [NVIDIA/NVTabular#710]
We are running tests only to see if the whole inference pipeline is working or not. But, we also need to check if there is any change for the expected accuracy. In the bug reported here https://github.com/NVIDIA/NVTabular/issues/707, the accuracy of the NVTabular + HugeCTR is below the expected level even though the whole inference pipeline works.

**Comment by benfred** [comment]
Done with #735
