### ISSUE TITLE
[FEA] Multihot support for PyTorch Inference

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [NVIDIA/NVTabular#719]
Current version of PyTorch inference only supports one hot. Add multihot support.

**Comment by benfred** [comment]
We will need this for session-based inference as well

**Comment by viswa-nvidia** [comment]
This issue was previously in the NVTabular v0.6 milestone. Moving it to v21.09

**Comment by benfred** [comment]
mostly done with #1078 - an integration test will come after
