### ISSUE TITLE
[TASK] Test Google Cloud support

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#72]
We should test our support for reading datasets from GCS, and running on GCP.

We should also write some documentation on getting started on running on GCP, as well as a sense of the performance to expect comparing GCS to local nvme drives

**Comment by benfred** [comment]
Basic support should be added with https://github.com/NVIDIA/NVTabular/pull/131 - but we should add some tests around this to verify

**Comment by benfred** [comment]
@EvenOldridge fyi

**Comment by EvenOldridge** [comment]
Do we want a separate ticket for AWS testing as well?

**Comment by benfred** [comment]
@gabrielspmoreira fyi -
