### ISSUE TITLE
[FEA] Return embedding table shape by feeding colum group to get_embedding_sizes() function

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#732]
**Is your feature request related to a problem? Please describe.**

In the current case, to get the embedding table shape, we need to do as follows:
```
cat_features = ['col'] >> Cateforify()
workflow = nvt.Workflow(cat_features) 
dataset = nvt.Dataset(gdf)
workflow.fit(dataset)
EMBEDDING_TABLE_SHAPES = nvt.ops.get_embedding_sizes(workflow)
```

but if we do have many other features from other ops, and not want to add `cat_features`  in the final workflow, we cannot get  embedding table shape from `nvt.ops.get_embedding_sizes(workflow)` because it would return {}.  

To avoid that can we change `def get_embedding_sizes(workflow):` to `def get_embedding_sizes(ColumnGroups):`
 or something like that so that we can run `nvt.ops.get_embedding_sizes(cat_features)` instead.

https://github.com/NVIDIA/NVTabular/blob/c7b7e05564ea675f00cad6e784cc360f8bb4ee85/nvtabular/ops/categorify.py#L449

**Comment by rnyak** [comment]
@gabrielspmoreira for viz.

**Comment by benfred** [comment]
This is possible now, but the api is a little clunky:

```python
cat_features.op.get_embedding_sizes(cat_features.columns)
```

**Comment by rnyak** [comment]
> This is possible now, but the api is a little clunky:
> 
> ```python
> cat_features.op.get_embedding_sizes(cat_features.columns)
> ```

Thanks Ben. will try it out.

**Comment by gabrielspmoreira** [comment]
Thanks @benfred . I have tried your suggested command and it does work.
`categ_features.op.get_embedding_sizes(categ_features.columns)`

The user could be interested to know only the cardinality of the categorical features and not our recommended embedding sizes. So maybe having a `get_categ_cardinalities()` could be interesting.
Furthermore, that function could be global to the workflow, making it clear that it is only available after the fit() call and returning a dict with the cardinality of all categorical features.
