### ISSUE TITLE
Evaluate Tensorflow Model Zoo Developed by Alec Gunny

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA/NVTabular#754]
Investigate the model zoo code at https://github.com/rapidsai/recsys/tree/main/static_benchmark and determine next steps for its development.

**Comment by karlhigley** [comment]
Took a look, with some work looks like it could turn into a `models` repo. Working to extract and refactor the models, so would consider the evaluation complete at this point. Tracking that work on the new repo.
