### ISSUE TITLE
[BUG] Total number of concatenated rows exceeds size_type range

### ISSUE THREAD

**Issue by RostislavStoyanov** [NVIDIA/NVTabular#770]
**Describe the bug**
Hello, after seeing your RecSys2020 tutorial, I've attempted to use NVTabular for preprocessing the data in the RecSysChallenge 2021. However when i try to use fit on my workflow i get a Runtime Error: `Total number of concatenated rows exceeds size_type range`. 

**Steps/Code to reproduce bug**
Notebook containing the code can be found here - https://github.com/RostislavStoyanov/recsys/blob/master/Preprocessing.ipynb

**Expected behavior**
I expect the fit to complete successfully.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of NVTabular install: conda
 

**Additional context**
Stack trace
```


---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/nvtabular-0.5.0-py3.8.egg/nvtabular/workflow.py in fit(self, dataset)
    140 
    141             if self.client:
--> 142                 results = [r.result() for r in self.client.compute(stats)]
    143             else:
    144                 results = dask.compute(stats, scheduler="synchronous")[0]

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/nvtabular-0.5.0-py3.8.egg/nvtabular/workflow.py in <listcomp>(.0)
    140 
    141             if self.client:
--> 142                 results = [r.result() for r in self.client.compute(stats)]
    143             else:
    144                 results = dask.compute(stats, scheduler="synchronous")[0]

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/distributed/client.py in result(self, timeout)
    218         if self.status == "error":
    219             typ, exc, tb = result
--> 220             raise exc.with_traceback(tb)
    221         elif self.status == "cancelled":
    222             raise result

~/anaconda3/envs/rapids-0.18/lib/python3.8/contextlib.py in inner()
     73         def inner(*args, **kwds):
     74             with self._recreate_cm():
---> 75                 return func(*args, **kwds)
     76         return inner
     77 

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/nvtabular-0.5.0-py3.8.egg/nvtabular/ops/categorify.py in _mid_level_groupby()

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/dataframe.py in from_arrow()
   5338             index_col = table.schema.pandas_metadata["index_columns"]
   5339 
-> 5340         out = super().from_arrow(table)
   5341 
   5342         if index_col:

~/anaconda3/envs/rapids-0.18/lib/python3.8/contextlib.py in inner()
     73         def inner(*args, **kwds):
     74             with self._recreate_cm():
---> 75                 return func(*args, **kwds)
     76         return inner
     77 

~/anaconda3/envs/rapids-0.18/lib/python3.8/site-packages/cudf/core/frame.py in from_arrow()
   2210             libcudf.table.Table()
   2211             if data.num_columns == 0
-> 2212             else libcudf.interop.from_arrow(data, data.column_names)
   2213         )
   2214 

cudf/_lib/interop.pyx in cudf._lib.interop.from_arrow()

RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1618503955512/work/cpp/src/copying/concatenate.cu:368: Total number of concatenated rows exceeds size_type range


```
Output in console 
```
distributed.worker - WARNING - Compute Failed
Function:  _mid_level_groupby
args:      ([pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: string
tweet_id_count: int32, pyarrow.Table
tweet_id: st
kwargs:    {}
Exception: RuntimeError('cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1618503955512/work/cpp/src/copying/concatenate.cu:368: Total number of concatenated rows exceeds size_type range')
```

**Comment by benfred** [comment]
Hi @RostislavStoyanov - thanks for giving NVTabular a go!

I think the bug you're hitting here is because of an underlying restriction of cudf - each dataframe can only have a max of 2GB of data in a single string column.

Can you try reducing the partition sizes you're processing? You can do this by setting the ```part_size``` or ```part_mem_fraction``` parameters you pass to the [```nvtabular.Dataset``` object](https://nvidia.github.io/NVTabular/main/resources/api/dataset.html)

**Comment by RostislavStoyanov** [comment]
Reducing the `part_size` from 1GB to 256MB had no effect. I will try further reducing that parameter and report here. Not sure if it helps, but i am also using a `dask.distributed` client connected to a `LocalCudaCluster` for the `Workflow` object and i also run `client.run(cudf.set_allocator, "managed")` on that client (I do this because of memory issues).

**Comment by bschifferer** [comment]
Hello @RostislavStoyanov ,

thanks for trying out - sorry for my delayed response, I was on vacation.

The BUG, you discovered, is related to Categorifying the tweet_id and userids. We use `Categorify` op to map the original IDs to a continuous Integer, as they require less bytes to represent and easier to process. `Categorify` creates a mapping table from ID->Continuous Integer. In the RecSys2021 dataset, we have ~200M unique IDs and creating the mapping table for so many unique Strings gets difficult.

How to fix that? As we want to represent the tweet_id/user_id for processing reason as Integer, we can hash instead of using Categorify operation.

`gdf.hash_columns` output is a int32 - we have 2**64 buckets, the probability of a collusion should be pretty small.
After the IDs are int32, they requires less space and are easier to process (Categorify Ops is may possible to apply afterwards on it)

I tested the first step of recsys2020 workflow with ~150 of 253 files and it worked for me. It took ~2-3min for `.fit` and 4-5min for `.transform` with 8 GPUs.

From
```
cat_features = (['tweet_id', 'language', 'engaging_user_id', 'engaged_with_user_id'] + fill_miss >> nvt.ops.Categorify())
``` 
To
```
cat_features = (['language',] + fill_miss >> nvt.ops.Categorify())

tweet_id = (
    nvt.ColumnGroup("tweet_id") >> 
    (lambda col, gdf: gdf.hash_columns(['tweet_id']))
)
engaging_user_id = (
    nvt.ColumnGroup("engaging_user_id") >> 
    (lambda col, gdf: gdf.hash_columns(['engaging_user_id']))
)
engaged_with_user_id = (
    nvt.ColumnGroup("engaged_with_user_id") >> 
    (lambda col, gdf: gdf.hash_columns(['engaged_with_user_id']))
)
```

**Comment by RostislavStoyanov** [comment]
Hi @bschifferer,

Thank you for taking the time to help me. Unfortunately, I won't be able to test this until next week, but I will make sure to update this issue once I get back.

Also, considering this is happening, most likely, because of the cudf restriction, mentioned before, should this be considered a bug and have I made a mistake with labeling it as such?
