### ISSUE TITLE
Multi-GPU training with PyTorch Distributed

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA/NVTabular#775]

**Comment by karlhigley** [comment]
Someone on our Slack tried to do this by combining PyTorch DistributedDataParallel with the NVT dataloaders, and reported that the NVT dataloaders for PyTorch are not picklable, which may present an obstacle to native support for PyTorch Distributed:
![image](https://user-images.githubusercontent.com/885295/118318357-4855b480-b4c7-11eb-97a8-414eeae379b7.png)
