### ISSUE TITLE
[OP] add tolist() op, and combine two lists into a dict with dict(zip())

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#79]
**Is your feature request related to a problem? Please describe.**

W&D Outbrain model uses `tolist()` function to convert series to list. The lists are then combined into dictionary with `dict(zip())` method.

**Describe the solution you'd like**
We should be able to convert series to list, and combine them into a dictionary.

**Additional context**
cudf supports `tolist()` and `dict(zip())` methods. See example below:

```
gdf = cudf.DataFrame({'display_id':['1', '2', '3',  '4'], 'state':['CA', 'MI', 'WV',  'SC'], 'views':[5, 4, 10,  3]})

state_view = dict(zip(gdf['state'].tolist(), gdf['views'].tolist()))
state_view
{'CA': 5, 'MI': 4, 'WV': 10, 'SC': 3}
```

**Comment by alecgunny** [comment]
Is there a reason you need a dict? Wouldn't an easier solution here be to just use a Series and do
```
state_view = gdf.set_index('state')['views']
```

**Comment by rnyak** [comment]
@alecgunny that can be a workaround for us.

**Comment by benfred** [comment]
We are going to try to avoiding dictionaries

**Comment by benfred** [comment]
@rnyak - I'm going to close this because I don't think its necessary anymore. feel free to re-open if I'm wrong on this =)
