### ISSUE TITLE
[FEA] Enable workflow apply() to cudf Dataframe

### ISSUE THREAD

**Issue by kkranen** [NVIDIA/NVTabular#82]
**Is your feature request related to a problem? Please describe.**
Currently, NVTabular operations can be applied directly to cudf dataframes, however, workflows cannot be applied directly. For testing purposes before deployment, the ability to test on a basic toy cudf could improve development time, but this feature is not yet supported.

**Describe the solution you'd like**
A method to apply a workflow to a cudf dataframe rather than an nvt.dataset for testing purposes.

**Describe alternatives you've considered**
A method to easily wrap a cudf dataframe into a nvt.dataset.

**Additional context**

**Comment by benfred** [comment]
Done with #164
