### ISSUE TITLE
[BUG] Incorrect slot size in Movie lens hugeCTR training

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/NVTabular#837]
**Describe the bug**

In examples/getting-started-movielens/inference-HugeCTR/Training-with-HugeCTR.ipynb

Slot size should be consistent with the order in NVT _metadata.json.
which is:

{"file_stats": [{"file_name": "0.99877d58b8d64b85af137a5fe87f9e7b.parquet", "num_rows": 20000076}], "cats": [{"col_name": "userId", "index": 0}, {"col_name": "movieId", "index": 1}], "conts": [], "labels": [{"col_name": "rating", "index": 2}]}

So slot_size_array=[56586, 162542],
should be corrected as slot_size_array=[162542, 56586]

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 

**Additional context**

**Comment by vinhngx** [comment]
@rnyak  FYI

**Comment by rnyak** [comment]
@vinhngx thanks. will look into that. Strange that HugeCTR did not give error while training with the current slot sizes. I expect it should..
