### ISSUE TITLE
[BUG] Workflow.to_ddf() returns a Dask collection with incorrect metadata

### ISSUE THREAD

**Issue by rjzamora** [NVIDIA/NVTabular#852]
**Describe the bug**
This is actually an known issue, [with a clear comment/explanation in workflow.py](https://github.com/NVIDIA/NVTabular/blob/9e14acc4eeb103bdd9590fb2a28eb5a182151be2/nvtabular/workflow.py#L302).  Currently, `_transform_ddf` will pass [a contrived `meta` argument](https://github.com/NVIDIA/NVTabular/blob/9e14acc4eeb103bdd9590fb2a28eb5a182151be2/nvtabular/workflow.py#L307) to `map_partitions` to ensure that all dtypes will be set to "float".  This means that `Dataset.to_ddf` will return a Dask-collection with  "bad" metadata if the Dataset object was generated by `Workflow.transform`.  This can cause problems in follow-up Dask-Dataframe processing.  For example:

```python
import cudf
import dask_cudf
import nvtabular as nvt

# Inital Dataset
df = cudf.datasets.timeseries().reset_index()
ddf = dask_cudf.from_cudf(df, npartitions=2)
dataset = nvt.Dataset(ddf)

# Create and Execute Workflow
cols = ["name", "x", "y", "timestamp"]
cat_cols = ["id"] >> nvt.ops.Normalize()
workflow = nvt.Workflow(cols + cat_cols)
workflow.fit(dataset)
new = workflow.transform(dataset)

# Follow-Up Dask-cuDF Sorting Fails
# (Works fine if dtypes are explicitly cast to int and datetime)
new.to_ddf().sort_values(["id", "timestamp"]).compute()
```

 cc @rnyak

**Comment by rnyak** [comment]
Thanks @rjzamora
