### ISSUE TITLE
[BUG] Model' object has no attribute 'mh_cat_layer' error with only multi-hot columns when training PyT model

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#869]
**Describe the bug**
I am getting `AttributeError: 'Model' object has no attribute 'mh_cat_layer'`when I train my PyTorch model with only multi-hot columns.  

**Steps/Code to reproduce bug**
I used example in the [getting-started-with-movielens Pyt training nb](https://github.com/NVIDIA/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-PyTorch.ipynb).  I removed `CATEGORICAL_COLUMNS = ["movieId", "userId"]` single hot columns and trained model only with multi-hot columns `CATEGORICAL_MH_COLUMNS = ["genres"]` .

See the full error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

/nvtabular/nvtabular/framework_utils/torch/utils.py in process_epoch(dataloader, model, train, optimizer, loss_func, transform, amp, device)
    123             if amp:
    124                 with torch.cuda.amp.autocast():
--> 125                     y_pred = model(x_cat, x_cont)
    126                     y_pred_list.append(y_pred.detach())
    127                     loss = loss_func(y_pred, y)

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

/nvtabular/nvtabular/framework_utils/torch/models.py in forward(self, x_cat, x_cont)
     86             x_cat, mh_cat = x_cat
     87         if mh_cat:
---> 88             mh_cat = self.mh_cat_layer(mh_cat)
     89             concat_list.append(mh_cat)
     90         x_cat = self.initial_cat_layer(x_cat)

/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    945             if name in modules:
    946                 return modules[name]
--> 947         raise AttributeError("'{}' object has no attribute '{}'".format(
    948             type(self).__name__, name))
    949 

AttributeError: 'Model' object has no attribute 'mh_cat_layer'

```
**Expected behavior**

`Models.py` should be designed to work only with `multi-hot` columns as well. 

**Environment details (please complete the following information):**
 - Environment location: Docker `merlin-pytorch-training` 0.5.3 image (with latest main branch pulled)
 - Method of NVTabular install: Docker 
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Comment by rnyak** [comment]
@jperez999 FYI. Thanks.

**Comment by rnyak** [comment]
@karlhigley @jperez999  this  is a code example for the error.
[03-Training-with-PyTorch-v1.ipynb.zip](https://github.com/NVIDIA/NVTabular/files/6624789/03-Training-with-PyTorch-v1.ipynb.zip)

**Comment by karlhigley** [comment]
I think the issue might be the difference between:
```python
EMBEDDING_TABLE_SHAPES_TUPLE = (
    {
#         CATEGORICAL_COLUMNS[0]: EMBEDDING_TABLE_SHAPES[CATEGORICAL_COLUMNS[0]],
#         CATEGORICAL_COLUMNS[1]: EMBEDDING_TABLE_SHAPES[CATEGORICAL_COLUMNS[1]],
    },
    {CATEGORICAL_MH_COLUMNS[0]: MH_EMBEDDING_TABLE_SHAPES[CATEGORICAL_MH_COLUMNS[0]]}
)
EMBEDDING_TABLE_SHAPES_TUPLE
```
and
```python
EMBEDDING_TABLE_SHAPES_TUPLE = (
#    {
#         CATEGORICAL_COLUMNS[0]: EMBEDDING_TABLE_SHAPES[CATEGORICAL_COLUMNS[0]],
#         CATEGORICAL_COLUMNS[1]: EMBEDDING_TABLE_SHAPES[CATEGORICAL_COLUMNS[1]],
#    },
    {CATEGORICAL_MH_COLUMNS[0]: MH_EMBEDDING_TABLE_SHAPES[CATEGORICAL_MH_COLUMNS[0]]}
)
EMBEDDING_TABLE_SHAPES_TUPLE
```
which changes the shape of the tuple in way that leads the base PyTorch model to mis-interpret the multi-hot shapes as the single-hot shapes, fail to find any shapes for the multi-hots, and skip creating the `self.mh_cat_layer` attribute (since there are no shapes.)

When `Model.__init__()` gets to [these lines](https://github.com/NVIDIA/NVTabular/blob/02d1829ab7e1a43318d15b53cd3c2ed2c34818fa/nvtabular/framework_utils/torch/models.py#L55-L59) it sees a tuple with one element instead of a tuple where the first element is an empty dictionary and the second element is the multi-hot shapes, so it doesn't create a multi-hot embedding layer (because it doesn't know what shape to make it.)

This a bit of a rough edge in the API we might to smooth out somehow. 🤔
