### ISSUE TITLE
[BUG] Workflow `load` fails to load categorical encodings during `transform`

### ISSUE THREAD

**Issue by mkurovski** [NVIDIA/NVTabular#887]
Hi there,

**Describe the bug**
I create an `nvt.Workflow` object called `proc` which I fit to a given `nvt.Dataset` instance. Afterwards I save this object to an empty directory `proc.save(workflow_path)`.
If I try to load this workflow and transform the very same dataset in a separate Python process it fails since it cannot find the key for the first column in the dictionary where it tries to lookup the paths for the categorical encodings. It somehow doesn't seem to store them there in the first case since it yields a `KeyError`.

```
ailed to transform operator <nvtabular.ops.categorify.Categorify object at 0x7fc6f35759d0>
Traceback (most recent call last):
  File "/home/mkurovski/miniconda3/envs/recsys/lib/python3.8/site-packages/nvtabular-0.5.3+3.g50f04df-py3.8.egg/nvtabular/ops/categorify.py", line 397, in transform
    path = self.categories[storage_name]
KeyError: 'hashtags'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mkurovski/miniconda3/envs/recsys/lib/python3.8/site-packages/nvtabular-0.5.3+3.g50f04df-py3.8.egg/nvtabular/workflow.py", line 346, in _transform_partition
    df = column_group.op.transform(column_group.input_column_names, df)
  File "/home/mkurovski/miniconda3/envs/recsys/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/mkurovski/miniconda3/envs/recsys/lib/python3.8/site-packages/nvtabular-0.5.3+3.g50f04df-py3.8.egg/nvtabular/ops/categorify.py", line 417, in transform
    raise RuntimeError(f"Failed to categorical encode column {name}") from e
RuntimeError: Failed to categorical encode column hashtags
```

**Steps/Code to reproduce bug**

Steps to generate and save the corresponding workflow
```
trains_itrs = nvt.Dataset(
    filepaths,
    engine="parquet",
    part_size="2GB",
)
# all_feat_columns is a a <ColumnGroup + output> object that incorporates various feature columns with transformations like `Categorify`
proc = nvt.Workflow(all_feat_columns)
proc.fit(trains_itrs)

workflow_path = "/home/mkurovski/data/workflow/"
proc.save(workflow_path)
```

Steps to retrieve and apply the workflow (in a different session afterwards, time-wise decoupled)

```
workflow_path = "/home/mkurovski/data/workflow/"
os.listdir(workflow_path)  # returns ['categories', 'workflow.pkl', 'metadata.json']
trains_itrs = nvt.Dataset(
    filepaths,
    engine="parquet",
    part_size="2GB",
)
proc.load(workflow_path)  # returns <nvtabular.workflow.Workflow at 0x7fc548064370>

# this is where it fails with the error message above
proc.transform(trains_itrs).to_parquet(
    output_path=output_folder, preserve_files=True
)
```

**Expected behavior**
I expect it to find the paths properly when loading a persisted workflow. This seems to run into an error if you try to retrieve in in another session, so maybe it's not persisting the workflow properly in the first place.

**Environment details (please complete the following information):**
`nvtabular-0.5.3+3.g50f04df` installed from source

Happy to answer any follow-up questions
Thanks and Best Regards,
Marcel

**Comment by benfred** [comment]
```Workflow.load`` is a classmethod that works like an alternate constructor, and returns a Workflow object. 

Can you try
```python
proc = nvt.Workflow.load(workflow_path)
```
instead?

**Comment by mkurovski** [comment]
Thanks, this way it works!

**Comment by benfred** [comment]
Awesome - great!
