### ISSUE TITLE
[BUG] getting `dimension out or range` error from create_stack function 

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#890]
**Describe the bug**
getting the following error while trying to train a PyT model with NVT dataloader and functions:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<timed exec> in <module>
/nvtabular/nvtabular/framework_utils/torch/utils.py in process_epoch(dataloader, model, train, optimizer, loss_func, transform, amp, device)
    111         y_list, y_pred_list = [], []
    112         for idx, batch in enumerate(iter(dataloader)):
--> 113             x_cat, x_cont, y = transform(batch)
    114             if device:
    115                 x_cat = x_cat.to(device)
/nvtabular/nvtabular/framework_utils/torch/utils.py in transform(self, batch)
     50         # take a part the batch and put together into subsets
     51         if self.cats:
---> 52             cats = self.create_stack(batch, self.cats)
     53         if self.conts:
     54             conts, _ = self.create_stack(batch, self.conts)
/nvtabular/nvtabular/framework_utils/torch/utils.py in create_stack(self, batch, target_columns)
     70                 mh_s[column_name] = target
     71         if columns:
---> 72             columns = torch.cat(columns, 1)
     73         return columns, mh_s
     74 
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Environment details (please complete the following information):**
 - Environment location:  Docker, `merlin-pytorch-training` 0.5.3 image
 - Method of NVTabular install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Comment by benfred** [comment]
Can you post some instructions on how to reproduce?( https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports )

**Comment by rnyak** [comment]
@benfred I sent the reproducible material to @jperez999 but I will try to create a toy example.

**Comment by jperez999** [comment]
I have reproduced the issue and I am working on a fix. Still do not exactly know what the cause is, but it looks like that has to do with a pattern of data where you have 1 one-hot,  and multiple multi-hot columns going into the model.
