### ISSUE TITLE
[BUG] Update HugeCTR nbs wrt the major modifications about the HugeCTR Python interface

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#892]
**Describe the bug**
We received a msg from HugeCTR team that they are going to remove the binary executable usage and make some major modifications about the Python interface in their upcoming release. Since there are notebooks residing in Merlin repos that are using HugeCTR APIs, they should be updated accordingly.

Resources: [
HugeCTR Python Interface](https://gitlab-master.nvidia.com/dl/hugectr/hugectr/-/blob/v3.1-integration/docs/python_interface.md) and [HugeCTR criteo nb](https://gitlab-master.nvidia.com/dl/hugectr/hugectr/-/blob/v3.1-integration/notebooks/hugectr_criteo.ipynb)

One other point here is to be able to pull the latest changes from HugeCTR side so that we can use the `merlin-training` and `merlin-inference`  docker images with the latest changes, and work on the example nbs.

**Comment by benfred** [comment]
@bschifferer Kingsley should have an updated notebook with a demo of the new api tomorrow
