### ISSUE TITLE
[OP] Groupby aggregate into list 

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#92]
**Is your feature request related to a problem? Please describe.**

Groupby is a widely used  operation in W&D Outbrain model. One usage creates a grouped data frame with list entries. cuDF currently does not support that functionality. 

**Describe the solution you'd like**
I'd like to be able to get row entries as lists or nested types after groupby operation.

**Additional context**
Pandas support this operation (see example below).
```
import pd
a = pd.DataFrame({'doc_id': [1, 1, 2, 2, 3, 3], 'category_id': [1, 2, 3, 3, 5, 6], 'confidence_level': [0.92, 0.251, 0.352, 0.359, 0.978, 0.988]})
a_grouped= a.groupby('doc_id', as_index=False)['category_id', 'confidence_level'].agg(lambda x: list(x))
a_grouped

	doc_id	category_id	confidence_level
0	1	   [1, 2]	[0.92, 0.251]
1	2	   [3, 3]	[0.352, 0.359]
2	3	   [5, 6]	[0.978, 0.988]
```

**Comment by gabrielspmoreira** [comment]
This feature is mandatory for sequence-based and session-based recommendation as, for each training instance (user or session), interactions are represented as a sequence, sorted by a column (generally a timestamp). Each interaction feature (e.g. item id, item category id, timestamp) becomes and Array/List column, whose length is the sequence length, and the elements ordering match according to the sequence of interactions.

Example in **Pandas**:
```
#Ensuring that interactions are chronologically ordered
df.sort_values(['timestamp'], inplace=True)
df.groupby('session_id').agg({'item_id': list, {'category_id': list})
```

Example in **PySpark**:
```
from pyspark.sql.window import Window
sorting_window = Window.partitionBy('session_id').orderBy('timestamp')
sessions_df = interactions_df.select('session_id', 
                                     F.collect_list('item_id').over(sorting_window).alias('item_ids')
                                      F.collect_list('item_category_id').over(sorting_window).alias('category_ids')) 
                         .groupBy('session_id') \
                         .agg(F.max('item_ids').alias('item_ids'),
                              F.max('category_ids').alias('category_ids'))

```

**Comment by rnyak** [comment]
cudf GH issue created: https://github.com/rapidsai/cudf/issues/5620

**Comment by benfred** [comment]
Moving this to the 0.3 release: We're moving anything with cudf list support to 0.3 - and moving ahead with an outbrains workflow that doesn't require list columns for 0.2.

**Comment by benfred** [comment]
This works with cudf - and can be done out of NVT
