### ISSUE TITLE
Save output from Categorify op in a single table for HugeCTR

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA/NVTabular#946]

**Comment by shijieliu** [comment]
hi, @karlhigley some comments form hugectr side. 

1.  AFAIK, the basic idea about this feature is try to add some offset. I would like to double check with you if that it true?

2. If using offset to make key unique, where do we get the offset? I think the offset should be unchanged after user generate data, in this case, we need to store offset and use it when we want to generate more data in the future. But how do we make sure the offset is still large enough for future data preprocess? 

3. How do we deal with key that is negative number?

Looking forward to your reply. Thanks.
