### ISSUE TITLE
Conection refused

### ISSUE THREAD

**Issue by taquanghung1705199** [NVIDIA/NVTabular#968]
Iam use RTX 2060.
I follow the instructions of getting-started-movielens. When I get to step "We check if the server is alive." in notebook, I get these this error
![image](https://user-images.githubusercontent.com/59196403/126148752-064aa0d9-ad4f-4051-b3ff-9df2060d95ba.png)
![image](https://user-images.githubusercontent.com/59196403/126148800-69b9b0cb-dcf4-44ba-b9e5-6f5ce25c81a8.png)

How to fix it ? 
Please help me !

**Comment by bschifferer** [comment]
@taquanghung1705199 thanks for the feedback and trying it.

The inference example expects that a Triton Server is running on localhost on port 8000

In the notebook, we added the launch command:
```
docker run -it --gpus device=0 -p 8000:8000 -p 8001:8001 -p 8002:8002 -v ${PWD}:/model/ nvcr.io/nvidia/merlin/merlin-inference:0.5.2
```
and start the server with
```
tritonserver --model-repository=path_to_models --backend-config=tensorflow,version=2 --model-control-mode=explicit
```

Have you started the server? Can you check, if the server was launched successfully?

**Comment by taquanghung1705199** [comment]
hello @bschifferer 
![image](https://user-images.githubusercontent.com/59196403/126209577-08d7d3b1-a7c5-4169-ba6c-6473a5d595a3.png)

I started server but the error still exists

**Comment by taquanghung1705199** [comment]
I am resolved https://github.com/NVIDIA/NVTabular/issues/968#issue-947527545 but when load model is this error appear

How to fix it ?
![image](https://user-images.githubusercontent.com/59196403/126290272-9340cdb9-9c55-43de-9948-a5347c01de09.png)

**Comment by bschifferer** [comment]
@taquanghung1705199 do you still have an issue? I got an email notification about no version available, when you try to load the model, but I cannot find the issue in github?

**Comment by taquanghung1705199** [comment]
@bschifferer 
When I change 
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 **--ipc**=host nvcr.io/nvidia/merlin/merlin-tensorflow-training:0.5.3 /bin/bash
to 
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 **--net**=host nvcr.io/nvidia/merlin/merlin-tensorflow-training:0.5.3 /bin/bash
everything is resolved !!!
