### ISSUE TITLE
[BUG] Conda install ERROR

### ISSUE THREAD

**Issue by niluanwudidadi** [NVIDIA/NVTabular#97]
**Describe the bug**
When I use 
"conda install -c nvidia -c rapidsai -c numba -c conda-forge nvtabular python=3.7 cudatoolkit=10.2"
it reports 
![image](https://user-images.githubusercontent.com/20806678/84872698-cbeb0380-b0b4-11ea-8439-674028f0fd75.png)
So which version of anaconda should I use? Can any one show your emvironment configuration, Thanks.

**Comment by rnyak** [comment]
@niluanwudidadi Can you provide more details? what's your conda version installed ? what's your os version in Linux? also can you share the full error text? 

Is your cuda toolkit version 10.2?

**Comment by niluanwudidadi** [comment]
@rnyak I have solved this problem by using docker file，hah。My conda version is Anaconda3-2020.02-Linux-x86_64，os is ubuntu16.04。By the way, conda install seems hard to work，maybe is my network's duty，xd。Is there any detailed document for nvtabular?

**Comment by benfred** [comment]
This should be fixed with NVT 0.3 - you should be able to install with conda now
