### ISSUE TITLE
[BUG] nvt.Dataset(df).to_parquet(tmp, partition_on=col) saves parquet files without .parquet extension

### ISSUE THREAD

**Issue by rnyak** [NVIDIA/NVTabular#996]
**Describe the bug**

I run this script `nvt.Dataset(df).to_parquet(tmp, partition_on=col)` to save preprocessed dask-cudf or cudf file by partitioning on a given column but this does not save the files with `.parquet` extension. It saves them as `part.0` instead of `part.0.parquet`.

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] Docker 
 
 - Method of NVTabular install: [conda, Docker, or from source] Docker- 0.5.3 image with latest nvtabular main branch and also tested with `nvtabular-merlin-pytorch` nightly container. 

   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Comment by rnyak** [comment]
@rjzamora @benfred looks like adding `method="worker"` param in the `to_parquet(..)` function solves this issue. @rjzamora can you confirm if that's the solution. thanks.

**Comment by rjzamora** [comment]
>@rjzamora can you confirm if that's the solution

Thanks - This is good information, but we probably want to fix the default `method` setting to work as well.
